namespace FurpaMerkezApi.Infrastructure.Persistence.Axata.Models;

public sealed class ENT000
{
    public string? S00TESN { get; set; }
    public string? S00SIPN { get; set; }
    public string? S00KTUR { get; set; }
    public string? S00SORG { get; set; }
    public string? S00DKAN { get; set; }
    public string? S00TEST { get; set; }
    public string? S00TESS { get; set; }
    public string? S00SMUS { get; set; }
    public string? S00TMUS { get; set; }
    public string? S00TSEK { get; set; }
    public string? S00NKOD { get; set; }
    public string? S00FDRM { get; set; }
    public string? S00FBLK { get; set; }
    public string? S00SUSR { get; set; }
    public string? S00MSIP { get; set; }
    public string? S00SNOT { get; set; }
    public string? S00INT1 { get; set; }
    public string? S00INT2 { get; set; }
    public string? S00ACIN { get; set; }
    public decimal? S00ITAR { get; set; }
    public decimal? S00IZMN { get; set; }
    public string? S00IDOC { get; set; }
    public decimal? S00YUKN { get; set; }
    public string? S00SKOD { get; set; }
    public string? S00HTP1 { get; set; }
    public string? S00HTP2 { get; set; }
    public DateTime? S00CDAT { get; set; }
    public long S00ID { get; set; }
    public string? S00PLAKA { get; set; }
    public string? S00SIST { get; set; }
    public string? S00MALIK { get; set; }
    public string? S00TADR { get; set; }
    public byte? S00STAT { get; set; }
    public DateTime? S00UDAT { get; set; }
    public int? S00PRIO { get; set; }
    public long? ERP_ID { get; set; }
    public string? S00CARGO { get; set; }
    public bool? S00ISECOMM { get; set; }
    public string? S00EC_FIRADI { get; set; }
    public string? S00EC_UKOD { get; set; }
    public string? S00EC_ILKOD { get; set; }
    public string? S00EC_ILCE { get; set; }
    public string? S00EC_SEMT { get; set; }
    public string? S00EC_PKOD { get; set; }
    public string? S00EC_TEL1 { get; set; }
    public string? S00EC_TEL2 { get; set; }
    public string? S00EC_EMAIL { get; set; }
    public string? S00EC_PLATFORM { get; set; }
    public byte? S00EC_ISKAPODEME { get; set; }
    public decimal? S00EC_TUTAR { get; set; }
    public string? S00EC_HIZMETSEKLI { get; set; }
    public string? S00EC_TESLIMSEKLI { get; set; }
    public string? S00EC_ODEMESEKLI { get; set; }
    public DateTime? S00EC_KARGOTESZMN { get; set; }
    public string? S00EC_VERDA { get; set; }
    public string? S00EC_VERNO { get; set; }
    public string? S00EC_CARGOLABEL { get; set; }
    public long? Linked_ID { get; set; }
    public string? S00PLAKA2 { get; set; }
    public string? S00EC_TAHSEKLI { get; set; }
    public DateTime? S00EC_KARGOTESZMN2 { get; set; }
    public string? S00EC_NOT { get; set; }
    public long? S00EC_ISGIFT { get; set; }
}

public sealed class ENT001
{
    public string? S01SKOD { get; set; }
    public string? S01TESL { get; set; }
    public string? S01KALN { get; set; }
    public string? S01UKAL { get; set; }
    public string? S01FRDP { get; set; }
    public string? S01SKU { get; set; }
    public string? S01LOTN { get; set; }
    public decimal? S01MIKT { get; set; }
    public decimal? S01SIM { get; set; }
    public decimal? S01TMIK { get; set; }
    public string? S01MURU { get; set; }
    public decimal? S01MSTR { get; set; }
    public string? S01HKOD { get; set; }
    public string? S01ITIP { get; set; }
    public string? S01SARG { get; set; }
    public decimal? S01ITAR { get; set; }
    public decimal? S01IZMN { get; set; }
    public string? S01IDOC { get; set; }
    public decimal? S01PRICE { get; set; }
    public DateTime? S01CDAT { get; set; }
    public string? S01LOTN2 { get; set; }
    public string? S01LOTN3 { get; set; }
    public long S01ID { get; set; }
    public string? S01BNED { get; set; }
    public byte? S01STAT { get; set; }
    public DateTime? S01UDAT { get; set; }
    public string? S01DEPO { get; set; }
    public decimal? S01OSMIK { get; set; }
    public decimal? S01MYTR { get; set; }
    public string? S01NOT { get; set; }
    public long? ERP_ID { get; set; }
    public decimal? S01PICKSIM { get; set; }
    public long? Linked_ID { get; set; }
    public bool? S01ISBUNDLE { get; set; }
    public string? S01BUNDLESKU { get; set; }
    public string? S01BUNDLELINE { get; set; }
    public decimal? S01BUNDLEQTY { get; set; }
}

public sealed class ENT006
{
    public string? S06SKOD { get; set; }
    public string? S06OHTP { get; set; }
    public string? S06TESL { get; set; }
    public decimal? S06STAT { get; set; }
    public string? S06HKOD { get; set; }
    public string? S06HTIP { get; set; }
    public string? S06INUM { get; set; }
    public string? S06STTU { get; set; }
    public string? S06KAMN { get; set; }
    public string? S06REFN { get; set; }
    public string? S06IRST { get; set; }
    public string? S06IRSZ { get; set; }
    public string? S06SSIP { get; set; }
    public string? S06GBEK { get; set; }
    public string? S06PLKA { get; set; }
    public string? S06KONT { get; set; }
    public string? S06KAMT { get; set; }
    public string? S06ACIN { get; set; }
    public string? S06FSTR { get; set; }
    public string? S06RPRT { get; set; }
    public decimal? S06YUKN { get; set; }
    public decimal? S06ITAR { get; set; }
    public decimal? S06IZMN { get; set; }
    public decimal? S06TMTR { get; set; }
    public decimal? S06TMZM { get; set; }
    public string? S06DEPO { get; set; }
    public string? S06RSIP { get; set; }
    public string? S06FIRM { get; set; }
    public string? S06TFIR { get; set; }
    public long S06SIRA { get; set; }
    public string? S06FNAME { get; set; }
    public decimal? S06PERS { get; set; }
    public int? S06TMSSTAT { get; set; }
    public byte? S06ODSSTAT { get; set; }
    public string? S06NTIP { get; set; }
    public string? S06PLKA2 { get; set; }
    public string? S06SURUCU { get; set; }
    public string? S06IPTKOD { get; set; }
    public double? S06BAGR { get; set; }
    public double? S06NAGR { get; set; }
    public double? S06DESI { get; set; }
    public double? S06HACIM { get; set; }
    public string? S06KIMLIKNO { get; set; }
    public string? S06EXPLAKA { get; set; }
    public string? S06EXSEALNO { get; set; }
    public double? S06EXAGR { get; set; }
    public string? S06EXNAKKOD { get; set; }
}

public sealed class ENT007
{
    public string? S07SIRK { get; set; }
    public string? S07TESL { get; set; }
    public string? S07KALN { get; set; }
    public decimal? S07STAT { get; set; }
    public string? S07HKOD { get; set; }
    public string? S07SKOD { get; set; }
    public string? S07LOTN { get; set; }
    public decimal? S07MIKT { get; set; }
    public decimal? S07SIMM { get; set; }
    public decimal? S07TOPM { get; set; }
    public string? S07STTU { get; set; }
    public decimal? S07YUKN { get; set; }
    public decimal? S07ITAR { get; set; }
    public decimal? S07IZMN { get; set; }
    public decimal? S07TMTR { get; set; }
    public decimal? S07TMZM { get; set; }
    public string? S07KNED { get; set; }
    public string? S07LOTN2 { get; set; }
    public string? S07LOTN3 { get; set; }
    public string? S07BNED { get; set; }
    public decimal? S07MFIFO { get; set; }
    public long S07SIRA { get; set; }
    public string? S07FNAME { get; set; }
    public decimal? S07OSMIK { get; set; }
    public string? S07BARKOD { get; set; }
    public bool? S07ISEXTLINE { get; set; }
}

public sealed class ENT009
{
    public decimal? S09STAT { get; set; }
    public string? S09TESL { get; set; }
    public string? S09SIPN { get; set; }
    public string? S09HTIP { get; set; }
    public string? S09EHTP { get; set; }
    public string? S09SKOD { get; set; }
    public decimal? S09SYIL { get; set; }
    public decimal? S09SNO { get; set; }
    public decimal? S09YUKN { get; set; }
    public decimal? S09INUM { get; set; }
    public decimal? S09IRTR { get; set; }
    public decimal? S09IRZM { get; set; }
    public decimal? S09FSTR { get; set; }
    public string? S09PLKA { get; set; }
    public string? S09ATEL { get; set; }
    public string? S09SOFOR { get; set; }
    public string? S09NAKL { get; set; }
    public string? S09USER { get; set; }
    public decimal? S09ITIP { get; set; }
    public decimal? S09ISTR { get; set; }
    public decimal? S09ISZM { get; set; }
    public decimal? S09TMTR { get; set; }
    public decimal? S09TMZM { get; set; }
    public string? S09BSNO { get; set; }
    public byte? S09GSNS { get; set; }
    public long S09SIRA { get; set; }
    public string? S09DEPO { get; set; }
    public string? S09MALIK { get; set; }
    public string? S09CONT { get; set; }
    public decimal? S09CONA { get; set; }
    public string? S09FNAME { get; set; }
    public int? S09AMBSAY { get; set; }
    public double? S09DESI { get; set; }
    public int? S09TMSSTAT { get; set; }
    public int? S09TMSTESSTAT { get; set; }
    public decimal? S09TMSTESTAR { get; set; }
    public string? S09NAKTIPI { get; set; }
    public string? S09ATIPI { get; set; }
    public long? S09EXIRSNO { get; set; }
    public string? S09EWAYBILLNO { get; set; }
    public string? S09SEVKTIPI { get; set; }
    public decimal? S09BRUTAGR { get; set; }
    public Guid? S09GUID { get; set; }
    public string? S09KIMLIKNO { get; set; }
    public string? S09ACK1 { get; set; }
    public string? S09ACK2 { get; set; }
    public string? S09ACK3 { get; set; }
    public string? S09MUHURNO { get; set; }
    public string? S09FIRMA { get; set; }
}

public sealed class ENT009_DETAIL
{
    public long S09SIRA { get; set; }
    public byte? S09STAT { get; set; }
    public string? S09SKOD { get; set; }
    public string? S09DEPO { get; set; }
    public string? S09SIPN { get; set; }
    public string? S09KALN { get; set; }
    public string? S09REFSIP { get; set; }
    public string? S09HTIP { get; set; }
    public string? S09EHTP { get; set; }
    public string? S09MALIK { get; set; }
    public int? S09YUKN { get; set; }
    public string? S09BSNO { get; set; }
    public int? S09INUM { get; set; }
    public int? S09EXINUM { get; set; }
    public decimal? S09IRTR { get; set; }
    public decimal? S09IRZM { get; set; }
    public decimal? S09FSTR { get; set; }
    public string? S09PLKA { get; set; }
    public string? S09CONT { get; set; }
    public decimal? S09CONA { get; set; }
    public string? S09ATEL { get; set; }
    public string? S09SOFOR { get; set; }
    public string? S09NAKL { get; set; }
    public string? S09FORMAT { get; set; }
    public string? S09USER { get; set; }
    public int? S09ITIP { get; set; }
    public decimal? S09ISTR { get; set; }
    public decimal? S09ISZM { get; set; }
    public decimal? S09TMTR { get; set; }
    public decimal? S09TMZM { get; set; }
    public string? S09FNAME { get; set; }
    public int? S09IPTINUM { get; set; }
}

public sealed class ENT013
{
    public string? S13SKOD { get; set; }
    public string? S13HKOD { get; set; }
    public string? S13BNUM { get; set; }
    public string? S13KALN { get; set; }
    public string? S13AKOD { get; set; }
    public decimal? S13SIPT { get; set; }
    public string? S13SKU { get; set; }
    public string? S13LOT { get; set; }
    public string? S13FIRM { get; set; }
    public decimal? S13MIKT { get; set; }
    public decimal? S13SIM { get; set; }
    public decimal? S13TMIK { get; set; }
    public decimal? S13KTIP { get; set; }
    public decimal? S13ITAR { get; set; }
    public decimal? S13IZMN { get; set; }
    public decimal? S13TMTR { get; set; }
    public decimal? S13TMZM { get; set; }
    public string? S13UYER { get; set; }
    public string? S13TESS { get; set; }
    public string? S13MAKK { get; set; }
    public string? S13MALIK { get; set; }
    public string? S13IRSN { get; set; }
    public decimal? S13IRST { get; set; }
    public string? S13LOT2 { get; set; }
    public string? S13LOT3 { get; set; }
    public long S13ID { get; set; }
    public decimal? S13OSMIK { get; set; }
    public int? S13RAFOM { get; set; }
    public int? S13REFT { get; set; }
    public decimal? S13TEST { get; set; }
    public string? S13NOT1 { get; set; }
    public string? S13NOT2 { get; set; }
    public bool? S13ISRESERVED { get; set; }
    public long? ERP_ID { get; set; }
    public int? S13STAT { get; set; }
    public DateTime? S13RCVDATE { get; set; }
    public string? S13REFKAL { get; set; }
    public string? S13IPKOD { get; set; }
}

public sealed class ENT013_MST
{
    public string? S13SKOD { get; set; }
    public string? S13HKOD { get; set; }
    public string? S13BNUM { get; set; }
    public decimal? S13SIPT { get; set; }
    public decimal? S13TEST { get; set; }
    public string? S13AKOD { get; set; }
    public string? S13EHKD { get; set; }
    public string? S13REFN { get; set; }
    public string? S13FIRM { get; set; }
    public string? S13MALIK { get; set; }
    public string? S13IRSN { get; set; }
    public decimal? S13IRST { get; set; }
    public string? S13PLKA { get; set; }
    public string? S13SOFOR { get; set; }
    public string? S13TEL1 { get; set; }
    public string? S13TEL2 { get; set; }
    public string? S13SIST { get; set; }
    public decimal? S13KTIP { get; set; }
    public decimal? S13ITAR { get; set; }
    public decimal? S13IZMN { get; set; }
    public string? S13SSIP { get; set; }
    public long S13ID { get; set; }
    public string? S13NOT1 { get; set; }
    public string? S13NOT2 { get; set; }
    public string? S13NOT3 { get; set; }
    public long? ERP_ID { get; set; }
    public string? S13SFIRM { get; set; }
    public int? S13STAT { get; set; }
    public DateTime? S13RCVDATE { get; set; }
}
