namespace FurpaMerkezApi.Infrastructure.Modules.EntegrasyonIslemleri.AxataSenkronizasyonu;

internal static class AxataSynchronizationFetchProfileCatalog
{
    public static IReadOnlyCollection<AxataSynchronizationFetchProfileDefinition> Definitions { get; } =
    [
        new(
            "c01-outbound-delivery",
            "C01 Cikis Teslimati",
            "AXATA",
            "Mikro",
            AxataEndpointKind.Main,
            "getOutBoundDeliveryListAsync",
            AxataEndpointKind.Extended,
            "updIntegrationTableAsync",
            "01",
            "01",
            "C01",
            "0",
            "LiveAuditIntervention",
            "/api/integrations/axata-sync/live/axata/outbound-deliveries/c01/import",
            true),
        new(
            "c02-outbound-delivery",
            "C02 Musteri Cikis Teslimati",
            "AXATA",
            "Mikro",
            AxataEndpointKind.Main,
            "getOutBoundDeliveryListAsync",
            AxataEndpointKind.Extended,
            "updIntegrationTableAsync",
            "01",
            "01",
            "C02",
            "0",
            "PlannedLiveFetchImport",
            null,
            false),
        new(
            "c03-outbound-delivery",
            "C03 Ozel Cikis Teslimati",
            "AXATA",
            "Mikro",
            AxataEndpointKind.Main,
            "getOutBoundDeliveryListAsync",
            AxataEndpointKind.Extended,
            "updIntegrationTableAsync",
            "01",
            "01",
            "C03",
            "0",
            "PlannedLiveFetchImport",
            null,
            false),
        new(
            "c04-outbound-delivery",
            "C04 Ozel Cikis Teslimati (legacy query C4)",
            "AXATA",
            "Mikro",
            AxataEndpointKind.Main,
            "getOutBoundDeliveryListAsync",
            AxataEndpointKind.Extended,
            "updIntegrationTableAsync",
            "01",
            "01",
            "C4",
            "0",
            "PlannedLiveFetchImport",
            null,
            false),
        new(
            "g01-inbound-atf",
            "G01 Firma Mal Kabul / ATF",
            "AXATA",
            "Mikro",
            AxataEndpointKind.Main,
            "getInboundATFListAsync",
            AxataEndpointKind.Extended,
            "updIntegrationTableAsync",
            "01",
            "01",
            "G01",
            "0",
            "ManualAxataNativeImport",
            "/api/integrations/axata-sync/manual/axata/inbound-atf/company-receivings",
            false),
        new(
            "g02-inbound-delivery",
            "G02 Depolar Arasi Giris Teslimati",
            "AXATA",
            "Mikro",
            AxataEndpointKind.Main,
            "getInboundDeliveryListAsync",
            AxataEndpointKind.Extended,
            "updIntegrationTableAsync",
            "01",
            "01",
            "G02",
            "0",
            "PlannedLiveFetchImport",
            null,
            false),
        new(
            "inventory-count-ext-view",
            "AXATA EXT Dinamik Sayim",
            "AXATA",
            "Mikro",
            AxataEndpointKind.Extended,
            "getViewDataAsync",
            AxataEndpointKind.Extended,
            "updIntegrationTableAsync",
            "01",
            "01",
            "vw_stok_duzeltme",
            "0",
            "ManualIncomingImport",
            "/api/integrations/axata-sync/manual/incoming/inventory-counts",
            false)
    ];
}

internal sealed record AxataSynchronizationFetchProfileDefinition(
    string Code,
    string Name,
    string SourceSystem,
    string TargetSystem,
    AxataEndpointKind SourceEndpointKind,
    string FetchOperation,
    AxataEndpointKind AckEndpointKind,
    string AckOperation,
    string CompanyCode,
    string WarehouseCode,
    string? MovementType,
    string PendingStatus,
    string CurrentHandling,
    string? CurrentRoute,
    bool IsImplemented);

internal enum AxataEndpointKind
{
    Main = 1,
    Extended = 2
}
