// <auto-generated />
using System;
using FurpaMerkezApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FurpaMerkezApi.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260414143012_RestructurePermissionCatalog")]
    partial class RestructurePermissionCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_app_permissions_code");

                    b.ToTable("app_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("119a5e97-4947-4c87-9ffd-2d35e343ef53"),
                            Code = "roles.manage",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create, update and assign roles.",
                            Name = "Manage Roles"
                        },
                        new
                        {
                            Id = new Guid("79925722-5c18-4db4-9c7d-c44d6f6fd779"),
                            Code = "permissions.manage",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create and update permissions.",
                            Name = "Manage Permissions"
                        },
                        new
                        {
                            Id = new Guid("fdf63a66-e9b4-4ca5-8700-2a6a34231c01"),
                            Code = "users.manage",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update users and assign roles.",
                            Name = "Manage Users"
                        },
                        new
                        {
                            Id = new Guid("56859677-3c5b-4935-b95c-3dfdfc295c64"),
                            Code = "order-operations.received-warehouse-orders.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View the received warehouse order list.",
                            Name = "List Received Warehouse Orders"
                        },
                        new
                        {
                            Id = new Guid("48299ef2-7866-4890-9537-6f7ab756d3a4"),
                            Code = "order-operations.received-warehouse-orders.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View a single received warehouse order.",
                            Name = "View Received Warehouse Order Detail"
                        },
                        new
                        {
                            Id = new Guid("23f24b09-fdf8-48b4-b064-463266c7b01b"),
                            Code = "order-operations.received-warehouse-orders.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new received warehouse orders.",
                            Name = "Create Received Warehouse Order"
                        },
                        new
                        {
                            Id = new Guid("a3064a06-c287-4be5-a39b-9bbc9d145839"),
                            Code = "order-operations.received-warehouse-orders.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update existing received warehouse orders.",
                            Name = "Update Received Warehouse Order"
                        },
                        new
                        {
                            Id = new Guid("8ff01b24-aa35-4b5b-b4f6-4a0a74ad9ff0"),
                            Code = "order-operations.supplier-orders.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View the supplier order list.",
                            Name = "List Supplier Orders"
                        },
                        new
                        {
                            Id = new Guid("318711ff-f0ed-45e2-b55e-ee93f8f1fe36"),
                            Code = "order-operations.supplier-orders.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View a single supplier order.",
                            Name = "View Supplier Order Detail"
                        },
                        new
                        {
                            Id = new Guid("2f1f08c8-40fc-4c7a-b2ad-0b96a42b32ea"),
                            Code = "order-operations.supplier-orders.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new supplier orders.",
                            Name = "Create Supplier Order"
                        },
                        new
                        {
                            Id = new Guid("80d80a6c-f985-42d9-8f24-3d62f010f4af"),
                            Code = "order-operations.supplier-orders.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update existing supplier orders.",
                            Name = "Update Supplier Order"
                        },
                        new
                        {
                            Id = new Guid("8c86e0d6-507a-4d16-9bb5-b745fcb054f7"),
                            Code = "shipment-operations.inter-warehouse-transfers.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View the inter-warehouse transfer list.",
                            Name = "List Inter-Warehouse Transfers"
                        },
                        new
                        {
                            Id = new Guid("e604251d-f4f8-4510-a3c0-a2044b1bcff3"),
                            Code = "shipment-operations.inter-warehouse-transfers.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View a single inter-warehouse transfer.",
                            Name = "View Inter-Warehouse Transfer Detail"
                        },
                        new
                        {
                            Id = new Guid("e9eb2dd0-9289-427f-ae0d-93dfe0fe726f"),
                            Code = "shipment-operations.inter-warehouse-transfers.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new inter-warehouse transfers.",
                            Name = "Create Inter-Warehouse Transfer"
                        },
                        new
                        {
                            Id = new Guid("949329f5-0c22-4b84-b45d-8a701a949a3d"),
                            Code = "shipment-operations.inter-warehouse-transfers.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update existing inter-warehouse transfers.",
                            Name = "Update Inter-Warehouse Transfer"
                        });
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_app_roles_name");

                    b.ToTable("app_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator role with all permissions.",
                            IsActive = true,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("app_role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("119a5e97-4947-4c87-9ffd-2d35e343ef53"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("79925722-5c18-4db4-9c7d-c44d6f6fd779"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("fdf63a66-e9b4-4ca5-8700-2a6a34231c01"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("56859677-3c5b-4935-b95c-3dfdfc295c64"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("48299ef2-7866-4890-9537-6f7ab756d3a4"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("23f24b09-fdf8-48b4-b064-463266c7b01b"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("a3064a06-c287-4be5-a39b-9bbc9d145839"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("8ff01b24-aa35-4b5b-b4f6-4a0a74ad9ff0"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("318711ff-f0ed-45e2-b55e-ee93f8f1fe36"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("2f1f08c8-40fc-4c7a-b2ad-0b96a42b32ea"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("80d80a6c-f985-42d9-8f24-3d62f010f4af"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("8c86e0d6-507a-4d16-9bb5-b745fcb054f7"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("e604251d-f4f8-4510-a3c0-a2044b1bcff3"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("e9eb2dd0-9289-427f-ae0d-93dfe0fe726f"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("949329f5-0c22-4b84-b45d-8a701a949a3d"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("warehouse_name");

                    b.Property<string>("WarehouseNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("warehouse_no");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_app_users_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_app_users_normalized_username");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("app_user_roles", (string)null);
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppRolePermission", b =>
                {
                    b.HasOne("FurpaMerkezApi.Domain.Entities.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurpaMerkezApi.Domain.Entities.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppUserRole", b =>
                {
                    b.HasOne("FurpaMerkezApi.Domain.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurpaMerkezApi.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
