// <auto-generated />
using System;
using FurpaMerkezApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FurpaMerkezApi.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260416104423_AddCompanyShipmentAndReturnPermissions")]
    partial class AddCompanyShipmentAndReturnPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_app_permissions_code");

                    b.ToTable("app_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("119a5e97-4947-4c87-9ffd-2d35e343ef53"),
                            Code = "kullanici-islemleri.roller.manage",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KullaniciIslemleri > Roller > Yonet yetkisi.",
                            Name = "Roller Yonet"
                        },
                        new
                        {
                            Id = new Guid("79925722-5c18-4db4-9c7d-c44d6f6fd779"),
                            Code = "kullanici-islemleri.yetkiler.manage",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KullaniciIslemleri > Yetkiler > Yonet yetkisi.",
                            Name = "Yetkiler Yonet"
                        },
                        new
                        {
                            Id = new Guid("fdf63a66-e9b4-4ca5-8700-2a6a34231c01"),
                            Code = "kullanici-islemleri.kullanicilar.manage",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KullaniciIslemleri > Kullanicilar > Yonet yetkisi.",
                            Name = "Kullanicilar Yonet"
                        },
                        new
                        {
                            Id = new Guid("b33d1d66-e2be-57c6-e4b3-f49080e36312"),
                            Code = "siparis-islemleri.alinan-depo-siparisleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > AlinanDepoSiparisleri > Listele yetkisi.",
                            Name = "AlinanDepoSiparisleri Listele"
                        },
                        new
                        {
                            Id = new Guid("a1e4861f-cdcb-532e-e9f1-08e984d770a6"),
                            Code = "siparis-islemleri.alinan-depo-siparisleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > AlinanDepoSiparisleri > Detay yetkisi.",
                            Name = "AlinanDepoSiparisleri Detay"
                        },
                        new
                        {
                            Id = new Guid("7195883f-f16d-baea-fea6-189050aa0b69"),
                            Code = "siparis-islemleri.alinan-depo-siparisleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > AlinanDepoSiparisleri > Ekle yetkisi.",
                            Name = "AlinanDepoSiparisleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("c9fb1ab0-900b-ebb3-502f-29803ea66f73"),
                            Code = "siparis-islemleri.alinan-depo-siparisleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > AlinanDepoSiparisleri > Guncelle yetkisi.",
                            Name = "AlinanDepoSiparisleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("42719ec3-0fe1-e97d-825d-5c9fe42594b4"),
                            Code = "siparis-islemleri.verilen-depo-siparisleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > VerilenDepoSiparisleri > Listele yetkisi.",
                            Name = "VerilenDepoSiparisleri Listele"
                        },
                        new
                        {
                            Id = new Guid("c617022a-192a-8579-98c9-2e8ae71873b1"),
                            Code = "siparis-islemleri.verilen-depo-siparisleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > VerilenDepoSiparisleri > Detay yetkisi.",
                            Name = "VerilenDepoSiparisleri Detay"
                        },
                        new
                        {
                            Id = new Guid("9bd65dad-0bf1-ae43-12ae-2af790f6103a"),
                            Code = "siparis-islemleri.verilen-depo-siparisleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > VerilenDepoSiparisleri > Ekle yetkisi.",
                            Name = "VerilenDepoSiparisleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("03f3bca3-0670-619a-d6e1-9da9cf4a759c"),
                            Code = "siparis-islemleri.verilen-depo-siparisleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > VerilenDepoSiparisleri > Guncelle yetkisi.",
                            Name = "VerilenDepoSiparisleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("608b0c7e-a2da-5e4a-6f2b-00736ebdc5f7"),
                            Code = "siparis-islemleri.alinan-firma-siparisleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > AlinanFirmaSiparisleri > Listele yetkisi.",
                            Name = "AlinanFirmaSiparisleri Listele"
                        },
                        new
                        {
                            Id = new Guid("d1e35eac-313d-b9e0-1fe2-6e4ad3e29117"),
                            Code = "siparis-islemleri.alinan-firma-siparisleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > AlinanFirmaSiparisleri > Detay yetkisi.",
                            Name = "AlinanFirmaSiparisleri Detay"
                        },
                        new
                        {
                            Id = new Guid("26dba67f-ab23-495f-e360-94933649a26a"),
                            Code = "siparis-islemleri.alinan-firma-siparisleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > AlinanFirmaSiparisleri > Ekle yetkisi.",
                            Name = "AlinanFirmaSiparisleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("a9e11671-15d8-6ca3-9317-ac8ef1129dee"),
                            Code = "siparis-islemleri.alinan-firma-siparisleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > AlinanFirmaSiparisleri > Guncelle yetkisi.",
                            Name = "AlinanFirmaSiparisleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("1fc04da2-9486-4a6c-04cb-d4022706d928"),
                            Code = "siparis-islemleri.verilen-firma-siparisleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > VerilenFirmaSiparisleri > Listele yetkisi.",
                            Name = "VerilenFirmaSiparisleri Listele"
                        },
                        new
                        {
                            Id = new Guid("7aec07c7-50e5-84f3-9787-c23842130105"),
                            Code = "siparis-islemleri.verilen-firma-siparisleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > VerilenFirmaSiparisleri > Detay yetkisi.",
                            Name = "VerilenFirmaSiparisleri Detay"
                        },
                        new
                        {
                            Id = new Guid("f63bad15-ce3b-0e08-eb0d-4e8ce49b755c"),
                            Code = "siparis-islemleri.verilen-firma-siparisleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > VerilenFirmaSiparisleri > Ekle yetkisi.",
                            Name = "VerilenFirmaSiparisleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("96dd46d0-cab5-1833-8804-30cad0c68c2e"),
                            Code = "siparis-islemleri.verilen-firma-siparisleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SiparisIslemleri > VerilenFirmaSiparisleri > Guncelle yetkisi.",
                            Name = "VerilenFirmaSiparisleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("90695dec-7135-8331-8a53-cc0b108a364c"),
                            Code = "sevk-islemleri.depolar-arasi-sevkler.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > DepolarArasiSevkler > Listele yetkisi.",
                            Name = "DepolarArasiSevkler Listele"
                        },
                        new
                        {
                            Id = new Guid("524b256e-b696-ccd1-6e28-481adb431a5b"),
                            Code = "sevk-islemleri.depolar-arasi-sevkler.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > DepolarArasiSevkler > Detay yetkisi.",
                            Name = "DepolarArasiSevkler Detay"
                        },
                        new
                        {
                            Id = new Guid("1e557c20-df49-dac6-dc69-b0aa103560d4"),
                            Code = "sevk-islemleri.depolar-arasi-sevkler.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > DepolarArasiSevkler > Ekle yetkisi.",
                            Name = "DepolarArasiSevkler Ekle"
                        },
                        new
                        {
                            Id = new Guid("b6abd05b-a3ea-7282-7655-b28f1f0a26b1"),
                            Code = "sevk-islemleri.depolar-arasi-sevkler.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > DepolarArasiSevkler > Guncelle yetkisi.",
                            Name = "DepolarArasiSevkler Guncelle"
                        },
                        new
                        {
                            Id = new Guid("2cb773b0-fb98-357e-103a-d4f1c6b62f78"),
                            Code = "sevk-islemleri.firma-sevkleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > FirmaSevkleri > Listele yetkisi.",
                            Name = "FirmaSevkleri Listele"
                        },
                        new
                        {
                            Id = new Guid("90a43d70-aa52-a61c-45aa-a07defb35d1a"),
                            Code = "sevk-islemleri.firma-sevkleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > FirmaSevkleri > Detay yetkisi.",
                            Name = "FirmaSevkleri Detay"
                        },
                        new
                        {
                            Id = new Guid("218c674f-77bb-027c-9e68-dfbf9e2f6cf0"),
                            Code = "sevk-islemleri.firma-sevkleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > FirmaSevkleri > Ekle yetkisi.",
                            Name = "FirmaSevkleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("7933b9ad-9225-22ad-6003-f91158f0cd95"),
                            Code = "sevk-islemleri.firma-sevkleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > FirmaSevkleri > Guncelle yetkisi.",
                            Name = "FirmaSevkleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("2e05f41f-3e70-647d-b2c4-0de5b71b45fb"),
                            Code = "sevk-islemleri.sevk-planlari.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > SevkPlanlari > Listele yetkisi.",
                            Name = "SevkPlanlari Listele"
                        },
                        new
                        {
                            Id = new Guid("1c957882-c345-0563-b714-044a014b3685"),
                            Code = "sevk-islemleri.sevk-planlari.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > SevkPlanlari > Detay yetkisi.",
                            Name = "SevkPlanlari Detay"
                        },
                        new
                        {
                            Id = new Guid("9af7b27e-33f6-715b-d009-f3a7bf177075"),
                            Code = "sevk-islemleri.sevk-planlari.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > SevkPlanlari > Ekle yetkisi.",
                            Name = "SevkPlanlari Ekle"
                        },
                        new
                        {
                            Id = new Guid("298fe457-a222-8a88-e870-2a812e93c8c6"),
                            Code = "sevk-islemleri.sevk-planlari.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SevkIslemleri > SevkPlanlari > Guncelle yetkisi.",
                            Name = "SevkPlanlari Guncelle"
                        },
                        new
                        {
                            Id = new Guid("a31529a2-aece-96f0-b8c2-6a62542d6952"),
                            Code = "iade-islemleri.firma-iadeleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > FirmaIadeleri > Listele yetkisi.",
                            Name = "FirmaIadeleri Listele"
                        },
                        new
                        {
                            Id = new Guid("0d7dcfaa-7fa9-f498-82dc-14a65b04b56e"),
                            Code = "iade-islemleri.firma-iadeleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > FirmaIadeleri > Detay yetkisi.",
                            Name = "FirmaIadeleri Detay"
                        },
                        new
                        {
                            Id = new Guid("31b8a318-b257-4a55-6cfd-817114486445"),
                            Code = "iade-islemleri.firma-iadeleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > FirmaIadeleri > Ekle yetkisi.",
                            Name = "FirmaIadeleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("c137720a-6a3d-04e8-64a8-56bfb278fec0"),
                            Code = "iade-islemleri.firma-iadeleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > FirmaIadeleri > Guncelle yetkisi.",
                            Name = "FirmaIadeleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("d01a6f35-5dc4-17a5-ba91-43fb7a870d74"),
                            Code = "mal-kabul-islemleri.mal-kabuller.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MalKabulIslemleri > MalKabuller > Listele yetkisi.",
                            Name = "MalKabuller Listele"
                        },
                        new
                        {
                            Id = new Guid("f0d1cc11-9d18-ea2c-6937-5aedfe2cb211"),
                            Code = "mal-kabul-islemleri.mal-kabuller.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MalKabulIslemleri > MalKabuller > Detay yetkisi.",
                            Name = "MalKabuller Detay"
                        },
                        new
                        {
                            Id = new Guid("693f14b5-0c0e-4902-9ec1-2441bba53003"),
                            Code = "mal-kabul-islemleri.mal-kabuller.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MalKabulIslemleri > MalKabuller > Ekle yetkisi.",
                            Name = "MalKabuller Ekle"
                        },
                        new
                        {
                            Id = new Guid("eeb59bad-31a8-ce76-6b64-7dc2326b1c7b"),
                            Code = "mal-kabul-islemleri.mal-kabuller.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MalKabulIslemleri > MalKabuller > Guncelle yetkisi.",
                            Name = "MalKabuller Guncelle"
                        },
                        new
                        {
                            Id = new Guid("da4d8624-84a7-c1cc-eb06-baef90f94422"),
                            Code = "mal-kabul-islemleri.irsaliye-kabulleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MalKabulIslemleri > IrsaliyeKabulleri > Listele yetkisi.",
                            Name = "IrsaliyeKabulleri Listele"
                        },
                        new
                        {
                            Id = new Guid("f3a84204-122d-27e5-b6af-8dd17b328f76"),
                            Code = "mal-kabul-islemleri.irsaliye-kabulleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MalKabulIslemleri > IrsaliyeKabulleri > Detay yetkisi.",
                            Name = "IrsaliyeKabulleri Detay"
                        },
                        new
                        {
                            Id = new Guid("0e7ee02d-a676-0224-dbc6-a2f529d93a2e"),
                            Code = "mal-kabul-islemleri.irsaliye-kabulleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MalKabulIslemleri > IrsaliyeKabulleri > Ekle yetkisi.",
                            Name = "IrsaliyeKabulleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("30b314b2-71d4-0960-0861-b6418dbd8f79"),
                            Code = "mal-kabul-islemleri.irsaliye-kabulleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MalKabulIslemleri > IrsaliyeKabulleri > Guncelle yetkisi.",
                            Name = "IrsaliyeKabulleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("381aca3b-27ca-8310-dc62-960634672984"),
                            Code = "iade-islemleri.musteri-iadeleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > MusteriIadeleri > Listele yetkisi.",
                            Name = "MusteriIadeleri Listele"
                        },
                        new
                        {
                            Id = new Guid("d476adc9-a850-a787-7525-a68429fbda72"),
                            Code = "iade-islemleri.musteri-iadeleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > MusteriIadeleri > Detay yetkisi.",
                            Name = "MusteriIadeleri Detay"
                        },
                        new
                        {
                            Id = new Guid("6867eb33-82ba-f745-b9fc-b950c650b04b"),
                            Code = "iade-islemleri.musteri-iadeleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > MusteriIadeleri > Ekle yetkisi.",
                            Name = "MusteriIadeleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("66c64021-d1e2-6cce-9ee6-77806ffb8e27"),
                            Code = "iade-islemleri.musteri-iadeleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > MusteriIadeleri > Guncelle yetkisi.",
                            Name = "MusteriIadeleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("88d9b895-3b28-f035-bc4c-d66bb274aac8"),
                            Code = "iade-islemleri.tedarikci-iadeleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > TedarikciIadeleri > Listele yetkisi.",
                            Name = "TedarikciIadeleri Listele"
                        },
                        new
                        {
                            Id = new Guid("a91159f2-6606-df6c-adff-fc380515ffa3"),
                            Code = "iade-islemleri.tedarikci-iadeleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > TedarikciIadeleri > Detay yetkisi.",
                            Name = "TedarikciIadeleri Detay"
                        },
                        new
                        {
                            Id = new Guid("35961219-4e49-744c-f302-d4e1b627c81d"),
                            Code = "iade-islemleri.tedarikci-iadeleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > TedarikciIadeleri > Ekle yetkisi.",
                            Name = "TedarikciIadeleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("143af022-4d7e-66eb-c558-624aad50fb7f"),
                            Code = "iade-islemleri.tedarikci-iadeleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IadeIslemleri > TedarikciIadeleri > Guncelle yetkisi.",
                            Name = "TedarikciIadeleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("22cb488c-9c07-29dc-e0a0-726025b88fc1"),
                            Code = "kasa-islemleri.kasa-hareketleri.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KasaIslemleri > KasaHareketleri > Listele yetkisi.",
                            Name = "KasaHareketleri Listele"
                        },
                        new
                        {
                            Id = new Guid("54ec0134-ed15-2ebc-b9c8-3208bd3ad0d9"),
                            Code = "kasa-islemleri.kasa-hareketleri.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KasaIslemleri > KasaHareketleri > Detay yetkisi.",
                            Name = "KasaHareketleri Detay"
                        },
                        new
                        {
                            Id = new Guid("22976e1d-77c4-5489-fe6d-c5db0aac96ad"),
                            Code = "kasa-islemleri.kasa-hareketleri.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KasaIslemleri > KasaHareketleri > Ekle yetkisi.",
                            Name = "KasaHareketleri Ekle"
                        },
                        new
                        {
                            Id = new Guid("5c60c66b-7679-bc4d-af47-11208ed6bb52"),
                            Code = "kasa-islemleri.kasa-hareketleri.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KasaIslemleri > KasaHareketleri > Guncelle yetkisi.",
                            Name = "KasaHareketleri Guncelle"
                        },
                        new
                        {
                            Id = new Guid("bd5765e8-6f52-a3e4-af46-54ff0b5ae4b2"),
                            Code = "kasa-islemleri.kasa-sayimlari.list",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KasaIslemleri > KasaSayimlari > Listele yetkisi.",
                            Name = "KasaSayimlari Listele"
                        },
                        new
                        {
                            Id = new Guid("0108f924-7db3-7ca6-c2ea-80ac5da8d9a4"),
                            Code = "kasa-islemleri.kasa-sayimlari.detail",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KasaIslemleri > KasaSayimlari > Detay yetkisi.",
                            Name = "KasaSayimlari Detay"
                        },
                        new
                        {
                            Id = new Guid("2fd4f83b-41dd-9fbb-d1d2-e40bdaa9f041"),
                            Code = "kasa-islemleri.kasa-sayimlari.create",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KasaIslemleri > KasaSayimlari > Ekle yetkisi.",
                            Name = "KasaSayimlari Ekle"
                        },
                        new
                        {
                            Id = new Guid("97b6ea99-c766-a946-5912-61af6ef2f0fe"),
                            Code = "kasa-islemleri.kasa-sayimlari.update",
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "KasaIslemleri > KasaSayimlari > Guncelle yetkisi.",
                            Name = "KasaSayimlari Guncelle"
                        });
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_app_roles_name");

                    b.ToTable("app_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator role with all permissions.",
                            IsActive = true,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("app_role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("119a5e97-4947-4c87-9ffd-2d35e343ef53"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("79925722-5c18-4db4-9c7d-c44d6f6fd779"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("fdf63a66-e9b4-4ca5-8700-2a6a34231c01"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("b33d1d66-e2be-57c6-e4b3-f49080e36312"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("a1e4861f-cdcb-532e-e9f1-08e984d770a6"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("7195883f-f16d-baea-fea6-189050aa0b69"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("c9fb1ab0-900b-ebb3-502f-29803ea66f73"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("42719ec3-0fe1-e97d-825d-5c9fe42594b4"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("c617022a-192a-8579-98c9-2e8ae71873b1"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("9bd65dad-0bf1-ae43-12ae-2af790f6103a"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("03f3bca3-0670-619a-d6e1-9da9cf4a759c"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("608b0c7e-a2da-5e4a-6f2b-00736ebdc5f7"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("d1e35eac-313d-b9e0-1fe2-6e4ad3e29117"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("26dba67f-ab23-495f-e360-94933649a26a"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("a9e11671-15d8-6ca3-9317-ac8ef1129dee"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("1fc04da2-9486-4a6c-04cb-d4022706d928"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("7aec07c7-50e5-84f3-9787-c23842130105"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("f63bad15-ce3b-0e08-eb0d-4e8ce49b755c"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("96dd46d0-cab5-1833-8804-30cad0c68c2e"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("90695dec-7135-8331-8a53-cc0b108a364c"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("524b256e-b696-ccd1-6e28-481adb431a5b"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("1e557c20-df49-dac6-dc69-b0aa103560d4"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("b6abd05b-a3ea-7282-7655-b28f1f0a26b1"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("2cb773b0-fb98-357e-103a-d4f1c6b62f78"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("90a43d70-aa52-a61c-45aa-a07defb35d1a"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("218c674f-77bb-027c-9e68-dfbf9e2f6cf0"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("7933b9ad-9225-22ad-6003-f91158f0cd95"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("2e05f41f-3e70-647d-b2c4-0de5b71b45fb"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("1c957882-c345-0563-b714-044a014b3685"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("9af7b27e-33f6-715b-d009-f3a7bf177075"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("298fe457-a222-8a88-e870-2a812e93c8c6"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("a31529a2-aece-96f0-b8c2-6a62542d6952"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("0d7dcfaa-7fa9-f498-82dc-14a65b04b56e"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("31b8a318-b257-4a55-6cfd-817114486445"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("c137720a-6a3d-04e8-64a8-56bfb278fec0"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("d01a6f35-5dc4-17a5-ba91-43fb7a870d74"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("f0d1cc11-9d18-ea2c-6937-5aedfe2cb211"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("693f14b5-0c0e-4902-9ec1-2441bba53003"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("eeb59bad-31a8-ce76-6b64-7dc2326b1c7b"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("da4d8624-84a7-c1cc-eb06-baef90f94422"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("f3a84204-122d-27e5-b6af-8dd17b328f76"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("0e7ee02d-a676-0224-dbc6-a2f529d93a2e"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("30b314b2-71d4-0960-0861-b6418dbd8f79"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("381aca3b-27ca-8310-dc62-960634672984"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("d476adc9-a850-a787-7525-a68429fbda72"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("6867eb33-82ba-f745-b9fc-b950c650b04b"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("66c64021-d1e2-6cce-9ee6-77806ffb8e27"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("88d9b895-3b28-f035-bc4c-d66bb274aac8"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("a91159f2-6606-df6c-adff-fc380515ffa3"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("35961219-4e49-744c-f302-d4e1b627c81d"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("143af022-4d7e-66eb-c558-624aad50fb7f"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("22cb488c-9c07-29dc-e0a0-726025b88fc1"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("54ec0134-ed15-2ebc-b9c8-3208bd3ad0d9"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("22976e1d-77c4-5489-fe6d-c5db0aac96ad"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("5c60c66b-7679-bc4d-af47-11208ed6bb52"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("bd5765e8-6f52-a3e4-af46-54ff0b5ae4b2"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("0108f924-7db3-7ca6-c2ea-80ac5da8d9a4"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("2fd4f83b-41dd-9fbb-d1d2-e40bdaa9f041"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            PermissionId = new Guid("97b6ea99-c766-a946-5912-61af6ef2f0fe"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("warehouse_name");

                    b.Property<string>("WarehouseNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("warehouse_no");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_app_users_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_app_users_normalized_username");

                    b.ToTable("app_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("af8e4919-5d2e-4c3a-981f-bafe1c1988ff"),
                            CreatedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@furpamerkez.local",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            NormalizedEmail = "ADMIN@FURPAMERKEZ.LOCAL",
                            NormalizedUsername = "ADMIN",
                            PasswordHash = "PBKDF2$100000$AAECAwQFBgcICQoLDA0ODw==$FdMPxR1Ml1GQMslxpUzbpxpAI5NoO/6gzn9FA8Rqaio=",
                            Username = "admin",
                            WarehouseName = "MERKEZ",
                            WarehouseNo = "0"
                        });
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("app_user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("af8e4919-5d2e-4c3a-981f-bafe1c1988ff"),
                            RoleId = new Guid("2ffb4f7d-b63d-4b12-8d74-e2a0aee2798a"),
                            AssignedAtUtc = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppRolePermission", b =>
                {
                    b.HasOne("FurpaMerkezApi.Domain.Entities.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurpaMerkezApi.Domain.Entities.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppUserRole", b =>
                {
                    b.HasOne("FurpaMerkezApi.Domain.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurpaMerkezApi.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FurpaMerkezApi.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
