namespace FurpaMerkezApi.Application.Modules.DuzeltmeIslemleri.MikroEvrakDuzenleme;

public sealed record StockCardSearchRequest(
    string? SearchText,
    bool IncludePassive,
    int Take);

public sealed record StockCardListItemDto(
    string StockCode,
    string Name,
    string ShortName,
    string SupplierCode,
    string Unit1Name,
    string MainGroupCode,
    string SubGroupCode,
    string CategoryCode,
    bool IsPassive,
    DateTime? LastUpdatedAt);

public sealed record StockCardDetailDto(
    string StockCode,
    string Name,
    string ShortName,
    string ForeignName,
    string SupplierCode,
    byte StockType,
    byte CurrencyType,
    byte TrackingType,
    string Unit1Name,
    string Unit2Name,
    string Unit3Name,
    string Unit4Name,
    byte RetailTaxPointer,
    byte WholesaleTaxPointer,
    string CategoryCode,
    string MainGroupCode,
    string SubGroupCode,
    string BrandCode,
    string SectorCode,
    string RayonCode,
    string ManufacturerCode,
    string ResponsibilityCode,
    string ShelfCode,
    bool SalesStopped,
    bool OrderStopped,
    bool ReceivingStopped,
    bool IsPassive,
    bool DiscountDisabled,
    DateTime CreatedAt,
    DateTime? LastUpdatedAt);

public sealed record StockCardPatchDto(
    string? Name,
    string? ShortName,
    string? ForeignName,
    string? SupplierCode,
    byte? StockType,
    byte? CurrencyType,
    byte? TrackingType,
    string? Unit1Name,
    string? Unit2Name,
    string? Unit3Name,
    string? Unit4Name,
    byte? RetailTaxPointer,
    byte? WholesaleTaxPointer,
    string? CategoryCode,
    string? MainGroupCode,
    string? SubGroupCode,
    string? BrandCode,
    string? SectorCode,
    string? RayonCode,
    string? ManufacturerCode,
    string? ResponsibilityCode,
    string? ShelfCode,
    bool? SalesStopped,
    bool? OrderStopped,
    bool? ReceivingStopped,
    bool? IsPassive,
    bool? DiscountDisabled);

public sealed record UpdateStockCardRequest(
    string StockCode,
    StockCardPatchDto Patch,
    int CurrentUserWarehouseNo);

public sealed record StockCardWarehouseSettingsDto(
    string StockCode,
    int WarehouseNo,
    string WarehouseName,
    bool HasWarehouseDetail,
    bool HasAnyOverride,
    bool GlobalSalesStopped,
    bool GlobalOrderStopped,
    bool GlobalReceivingStopped,
    bool GlobalIsPassive,
    bool GlobalDiscountDisabled,
    bool SalesStopped,
    bool OrderStopped,
    bool ReceivingStopped,
    bool IsPassive,
    bool DiscountDisabled,
    DateTime? LastUpdatedAt);

public sealed record StockCardWarehousePatchDto(
    bool? SalesStopped,
    bool? OrderStopped,
    bool? ReceivingStopped,
    bool? IsPassive,
    bool? DiscountDisabled,
    bool ResetToGlobal);

public sealed record UpdateStockCardWarehouseSettingsRequest(
    string StockCode,
    int WarehouseNo,
    StockCardWarehousePatchDto Patch,
    int CurrentUserWarehouseNo);

public sealed record WarehouseCardSearchRequest(
    string? SearchText,
    bool IncludePassive,
    int Take);

public sealed record WarehouseCardListItemDto(
    int WarehouseNo,
    string Name,
    string GroupCode,
    byte WarehouseType,
    string City,
    string District,
    bool IsPassive,
    bool IsHidden,
    DateTime? LastUpdatedAt);

public sealed record WarehouseCardDetailDto(
    Guid WarehouseGuid,
    int WarehouseNo,
    string Name,
    string GroupCode,
    byte WarehouseType,
    byte ShipmentAutoPriceType,
    byte MovementType,
    string AccountingCode,
    string ResponsibilityCenter,
    string ProjectCode,
    int ShipmentAppliedPriceNo,
    DateTime? LockDate,
    string Street,
    string Neighborhood,
    string Avenue,
    string Quarter,
    string ApartmentNo,
    string ApartmentUnitNo,
    string PostalCode,
    string District,
    string City,
    string Country,
    string AddressCode,
    double Latitude,
    double Longitude,
    string AuthorizedEmail,
    string PhoneCountryCode,
    string PhoneAreaCode,
    string PhoneNo1,
    string PhoneNo2,
    string FaxNo,
    bool ExcludedFromInventory,
    byte DetailTrackingType,
    string RegionCode,
    bool OutgoingEDespatchEnabled,
    bool IncomingEDespatchEnabled,
    bool IsPassive,
    bool IsHidden,
    bool IsLocked,
    DateTime CreatedAt,
    DateTime? LastUpdatedAt);

public sealed record WarehouseCardPatchDto(
    string? Name,
    string? GroupCode,
    byte? WarehouseType,
    byte? ShipmentAutoPriceType,
    byte? MovementType,
    string? AccountingCode,
    string? ResponsibilityCenter,
    string? ProjectCode,
    int? ShipmentAppliedPriceNo,
    DateTime? LockDate,
    string? Street,
    string? Neighborhood,
    string? Avenue,
    string? Quarter,
    string? ApartmentNo,
    string? ApartmentUnitNo,
    string? PostalCode,
    string? District,
    string? City,
    string? Country,
    string? AddressCode,
    double? Latitude,
    double? Longitude,
    string? AuthorizedEmail,
    string? PhoneCountryCode,
    string? PhoneAreaCode,
    string? PhoneNo1,
    string? PhoneNo2,
    string? FaxNo,
    bool? ExcludedFromInventory,
    byte? DetailTrackingType,
    string? RegionCode,
    bool? OutgoingEDespatchEnabled,
    bool? IncomingEDespatchEnabled,
    bool? IsPassive,
    bool? IsHidden,
    bool? IsLocked);

public sealed record UpdateWarehouseCardRequest(
    int WarehouseNo,
    WarehouseCardPatchDto Patch,
    int CurrentUserWarehouseNo);

public sealed record CustomerCardSearchRequest(
    string? SearchText,
    bool IncludePassive,
    int Take);

public sealed record CustomerCardListItemDto(
    string CustomerCode,
    string Title1,
    string Title2,
    string TaxOffice,
    string TaxNo,
    string GroupCode,
    string RegionCode,
    string RepresentativeCode,
    bool IsClosed,
    bool IsLocked,
    DateTime? LastUpdatedAt);

public sealed record CustomerCardDetailDto(
    Guid CustomerGuid,
    string CustomerCode,
    string Title1,
    string Title2,
    byte MovementType,
    byte ConnectionType,
    byte PurchaseStockType,
    byte SalesStockType,
    string AccountingCode,
    string AccountingCode1,
    string AccountingCode2,
    byte CurrencyType,
    byte CurrencyType1,
    byte CurrencyType2,
    string TaxOffice,
    string TaxOfficeNo,
    string RegistryNo,
    string TaxNo,
    int SalesPriceListNo,
    byte PaymentType,
    byte PaymentDay,
    int PaymentPlanNo,
    int OptionDay,
    int InvoiceAddressNo,
    int ShippingAddressNo,
    string ParentCustomerCode,
    string SectorCode,
    string RegionCode,
    string GroupCode,
    string RepresentativeCode,
    bool IsClosed,
    bool IsLocked,
    bool EInvoiceEnabled,
    byte DefaultEInvoiceType,
    bool EDespatchEnabled,
    byte DefaultEDespatchType,
    string Website,
    string Email,
    string MobilePhone,
    int DefaultInputWarehouseNo,
    int DefaultOutputWarehouseNo,
    string KepAddress,
    string ReconciliationEmail,
    string MersisNo,
    string TaxOfficeCode,
    bool RetailCustomer,
    DateTime CreatedAt,
    DateTime? LastUpdatedAt);

public sealed record CustomerCardPatchDto(
    string? Title1,
    string? Title2,
    byte? MovementType,
    byte? ConnectionType,
    byte? PurchaseStockType,
    byte? SalesStockType,
    string? AccountingCode,
    string? AccountingCode1,
    string? AccountingCode2,
    byte? CurrencyType,
    byte? CurrencyType1,
    byte? CurrencyType2,
    string? TaxOffice,
    string? TaxOfficeNo,
    string? RegistryNo,
    string? TaxNo,
    int? SalesPriceListNo,
    byte? PaymentType,
    byte? PaymentDay,
    int? PaymentPlanNo,
    int? OptionDay,
    int? InvoiceAddressNo,
    int? ShippingAddressNo,
    string? ParentCustomerCode,
    string? SectorCode,
    string? RegionCode,
    string? GroupCode,
    string? RepresentativeCode,
    bool? IsClosed,
    bool? IsLocked,
    bool? EInvoiceEnabled,
    byte? DefaultEInvoiceType,
    bool? EDespatchEnabled,
    byte? DefaultEDespatchType,
    string? Website,
    string? Email,
    string? MobilePhone,
    int? DefaultInputWarehouseNo,
    int? DefaultOutputWarehouseNo,
    string? KepAddress,
    string? ReconciliationEmail,
    string? MersisNo,
    string? TaxOfficeCode,
    bool? RetailCustomer);

public sealed record UpdateCustomerCardRequest(
    string CustomerCode,
    CustomerCardPatchDto Patch,
    int CurrentUserWarehouseNo);

public sealed record StockSalesPriceDto(
    Guid PriceGuid,
    string StockCode,
    int PriceListNo,
    string PriceListName,
    int WarehouseNo,
    string WarehouseName,
    int PaymentPlanNo,
    byte UnitPointer,
    string UnitName,
    double Price,
    byte CurrencyType,
    byte ChangeReason,
    DateTime CreatedAt,
    DateTime? LastUpdatedAt);

public sealed record UpsertStockSalesPriceRequest(
    string StockCode,
    int WarehouseNo,
    int PriceListNo,
    int PaymentPlanNo,
    byte UnitPointer,
    double Price,
    byte CurrencyType,
    byte ChangeReason,
    int CurrentUserWarehouseNo);

public sealed record StockSalesPriceUpsertResponse(
    MikroDocumentUpdateSummary Summary,
    bool Created,
    double? PreviousPrice,
    StockSalesPriceDto SalesPrice);

public sealed record StockMovementDocumentLookupRequest(
    string DocumentSerie,
    int DocumentOrderNo,
    byte? DocumentType,
    byte? MovementType,
    byte? MovementKind,
    byte? NormalReturn,
    int? WarehouseNo);

public sealed record StockMovementDocumentDto(
    StockMovementDocumentHeaderDto Header,
    IReadOnlyCollection<StockMovementDocumentLineDto> Lines);

public sealed record StockMovementDocumentHeaderDto(
    string DocumentSerie,
    int DocumentOrderNo,
    byte DocumentType,
    IReadOnlyCollection<byte> MovementTypes,
    byte MovementKind,
    byte NormalReturn,
    DateTime? MovementDate,
    DateTime? DocumentDate,
    DateTime? GoodsAcceptanceDate,
    string DocumentNo,
    string CustomerCode,
    string CustomerTitle,
    int InputWarehouseNo,
    string InputWarehouseName,
    int OutputWarehouseNo,
    string OutputWarehouseName,
    int ShippingWarehouseNo,
    string ShippingWarehouseName,
    string Description,
    string MovementGroupCode1,
    string MovementGroupCode2,
    string MovementGroupCode3,
    string CustomerResponsibilityCenter,
    string StockResponsibilityCenter,
    string ProjectCode,
    int LineCount,
    double TotalQuantity,
    double TotalAmount,
    DateTime CreatedAt,
    DateTime? LastUpdatedAt);

public sealed record StockMovementDocumentLineDto(
    Guid MovementGuid,
    int RowNo,
    DateTime? GoodsAcceptanceDate,
    string StockCode,
    string StockName,
    byte UnitPointer,
    string UnitName,
    double Quantity,
    double SecondaryQuantity,
    double UnitPrice,
    double Amount,
    double Discount1,
    double Discount2,
    double Discount3,
    double Discount4,
    double Discount5,
    double Discount6,
    double Expense1,
    double Expense2,
    double Expense3,
    double Expense4,
    byte TaxPointer,
    double TaxAmount,
    double NetWeight,
    double GrossWeight,
    string Description,
    string PartyCode,
    int LotNo,
    string ProjectCode,
    string CustomerResponsibilityCenter,
    string StockResponsibilityCenter,
    int InputWarehouseNo,
    int OutputWarehouseNo,
    DateTime? LastUpdatedAt);

public sealed record StockMovementHeaderPatchDto(
    DateTime? MovementDate,
    DateTime? DocumentDate,
    DateTime? GoodsAcceptanceDate,
    string? DocumentNo,
    string? CustomerCode,
    int? InputWarehouseNo,
    int? OutputWarehouseNo,
    int? ShippingWarehouseNo,
    string? Description,
    string? MovementGroupCode1,
    string? MovementGroupCode2,
    string? MovementGroupCode3,
    string? CustomerResponsibilityCenter,
    string? StockResponsibilityCenter,
    string? ProjectCode);

public sealed record StockMovementLinePatchDto(
    Guid MovementGuid,
    int? RowNo,
    DateTime? GoodsAcceptanceDate,
    string? StockCode,
    byte? UnitPointer,
    double? Quantity,
    double? SecondaryQuantity,
    double? Amount,
    double? Discount1,
    double? Discount2,
    double? Discount3,
    double? Discount4,
    double? Discount5,
    double? Discount6,
    double? Expense1,
    double? Expense2,
    double? Expense3,
    double? Expense4,
    byte? TaxPointer,
    double? TaxAmount,
    double? NetWeight,
    double? GrossWeight,
    string? Description,
    string? PartyCode,
    int? LotNo,
    string? ProjectCode,
    string? CustomerResponsibilityCenter,
    string? StockResponsibilityCenter,
    int? InputWarehouseNo,
    int? OutputWarehouseNo);

public sealed record UpdateStockMovementDocumentRequest(
    StockMovementDocumentLookupRequest Lookup,
    StockMovementHeaderPatchDto? Header,
    IReadOnlyCollection<StockMovementLinePatchDto> Lines,
    int CurrentUserWarehouseNo);

public sealed record CustomerMovementDocumentLookupRequest(
    string DocumentSerie,
    int DocumentOrderNo,
    byte? DocumentType,
    byte? MovementType,
    byte? MovementKind,
    byte? NormalReturn,
    string? CustomerCode);

public sealed record CustomerMovementDocumentDto(
    CustomerMovementDocumentHeaderDto Header,
    IReadOnlyCollection<CustomerMovementDocumentLineDto> Lines);

public sealed record CustomerMovementDocumentHeaderDto(
    string DocumentSerie,
    int DocumentOrderNo,
    byte DocumentType,
    IReadOnlyCollection<byte> MovementTypes,
    byte MovementKind,
    byte NormalReturn,
    DateTime? MovementDate,
    DateTime? DocumentDate,
    string DocumentNo,
    string CustomerCode,
    string TurnoverCustomerCode,
    string CustomerTitle,
    string Description,
    string SellerCode,
    string ProjectCode,
    string ResponsibilityCenter,
    int LineCount,
    double TotalQuantity,
    double TotalAmount,
    double TotalSubAmount,
    DateTime CreatedAt,
    DateTime? LastUpdatedAt);

public sealed record CustomerMovementDocumentLineDto(
    Guid MovementGuid,
    int RowNo,
    string CustomerCode,
    string TurnoverCustomerCode,
    string CustomerTitle,
    byte MovementType,
    byte MovementKind,
    byte NormalReturn,
    double Quantity,
    double Amount,
    double SubAmount,
    int DueDay,
    double Discount1,
    double Discount2,
    double Discount3,
    double Discount4,
    double Discount5,
    double Discount6,
    double Expense1,
    double Expense2,
    double Expense3,
    double Expense4,
    double Tax1,
    double Tax2,
    double Tax3,
    double Tax4,
    double Tax5,
    string Description,
    string SellerCode,
    string ProjectCode,
    string ResponsibilityCenter,
    DateTime? LastUpdatedAt);

public sealed record CustomerMovementHeaderPatchDto(
    DateTime? MovementDate,
    DateTime? DocumentDate,
    string? DocumentNo,
    string? CustomerCode,
    string? TurnoverCustomerCode,
    string? Description,
    string? SellerCode,
    string? ProjectCode,
    string? ResponsibilityCenter);

public sealed record CustomerMovementLinePatchDto(
    Guid MovementGuid,
    int? RowNo,
    string? CustomerCode,
    string? TurnoverCustomerCode,
    double? Quantity,
    double? Amount,
    double? SubAmount,
    int? DueDay,
    double? Discount1,
    double? Discount2,
    double? Discount3,
    double? Discount4,
    double? Discount5,
    double? Discount6,
    double? Expense1,
    double? Expense2,
    double? Expense3,
    double? Expense4,
    double? Tax1,
    double? Tax2,
    double? Tax3,
    double? Tax4,
    double? Tax5,
    string? Description,
    string? SellerCode,
    string? ProjectCode,
    string? ResponsibilityCenter);

public sealed record UpdateCustomerMovementDocumentRequest(
    CustomerMovementDocumentLookupRequest Lookup,
    CustomerMovementHeaderPatchDto? Header,
    IReadOnlyCollection<CustomerMovementLinePatchDto> Lines,
    int CurrentUserWarehouseNo);

public sealed record MikroDocumentUpdateSummary(
    string Target,
    int UpdatedRowCount,
    DateTime UpdatedAt,
    short UpdateUser);

public sealed record StockCardUpdateResponse(
    MikroDocumentUpdateSummary Summary,
    StockCardDetailDto StockCard);

public sealed record StockCardWarehouseUpdateResponse(
    MikroDocumentUpdateSummary Summary,
    StockCardWarehouseSettingsDto WarehouseSettings);

public sealed record WarehouseCardUpdateResponse(
    MikroDocumentUpdateSummary Summary,
    WarehouseCardDetailDto WarehouseCard);

public sealed record CustomerCardUpdateResponse(
    MikroDocumentUpdateSummary Summary,
    CustomerCardDetailDto CustomerCard);

public sealed record StockMovementDocumentUpdateResponse(
    MikroDocumentUpdateSummary Summary,
    StockMovementDocumentDto Document);

public sealed record CustomerMovementDocumentUpdateResponse(
    MikroDocumentUpdateSummary Summary,
    CustomerMovementDocumentDto Document);
