namespace FurpaMerkezApi.Application.Modules.DuzeltmeIslemleri.MikroEvrakDuzenleme;

public static class MikroDocumentFieldCatalog
{
    public static MikroDocumentFieldCatalogDto GetCatalog() =>
        new(
        [
            Section(
                "stock-card",
                "Stok Karti",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/stok-kartlari/{stockCode}",
                "StockCardPatchHttpRequest",
                "STOKLAR",
                [
                    Field("name", "Stok adi", "sto_isim", "string"),
                    Field("shortName", "Kisa ad", "sto_kisa_ismi", "string"),
                    Field("foreignName", "Yabanci ad", "sto_yabanci_isim", "string"),
                    Field("supplierCode", "Tedarikci cari kodu", "sto_sat_cari_kod", "string"),
                    Field("stockType", "Stok cinsi", "sto_cins", "byte"),
                    Field("currencyType", "Doviz cinsi", "sto_doviz_cinsi", "byte"),
                    Field("trackingType", "Detay takip tipi", "sto_detay_takip", "byte"),
                    Field("unit1Name", "Birim 1 adi", "sto_birim1_ad", "string"),
                    Field("unit2Name", "Birim 2 adi", "sto_birim2_ad", "string"),
                    Field("unit3Name", "Birim 3 adi", "sto_birim3_ad", "string"),
                    Field("unit4Name", "Birim 4 adi", "sto_birim4_ad", "string"),
                    Field("retailTaxPointer", "Perakende vergi pointer", "sto_perakende_vergi", "byte"),
                    Field("wholesaleTaxPointer", "Toptan vergi pointer", "sto_toptan_vergi", "byte"),
                    Field("categoryCode", "Kategori kodu", "sto_kategori_kodu", "string"),
                    Field("mainGroupCode", "Ana grup kodu", "sto_anagrup_kod", "string"),
                    Field("subGroupCode", "Alt grup kodu", "sto_altgrup_kod", "string"),
                    Field("brandCode", "Marka kodu", "sto_marka_kodu", "string"),
                    Field("sectorCode", "Sektor kodu", "sto_sektor_kodu", "string"),
                    Field("rayonCode", "Reyon kodu", "sto_reyon_kodu", "string"),
                    Field("manufacturerCode", "Uretici kodu", "sto_uretici_kodu", "string"),
                    Field("responsibilityCode", "Urun sorumluluk kodu", "sto_urun_sorkod", "string"),
                    Field("shelfCode", "Raf/yer kodu", "sto_yer_kod", "string"),
                    Field("special1", "Ozel kod 1", "sto_special1", "string", "En fazla 4 karakter."),
                    Field("special2", "Ozel kod 2", "sto_special2", "string", "En fazla 4 karakter."),
                    Field("special3", "Ozel kod 3", "sto_special3", "string", "En fazla 4 karakter."),
                    Field("salesStopped", "Satisa kapali", "sto_satis_dursun", "bool"),
                    Field("orderStopped", "Siparise kapali", "sto_siparis_dursun", "bool"),
                    Field("receivingStopped", "Mal kabule kapali", "sto_malkabul_dursun", "bool"),
                    Field("isPassive", "Pasif", "sto_pasif_fl", "bool"),
                    Field("discountDisabled", "Iskonto yapilamaz", "sto_iskon_yapilamaz", "bool")
                ]),
            Section(
                "stock-warehouse-settings",
                "Stok Depo Ayari",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/stok-kartlari/{stockCode}/depolar/{warehouseNo}",
                "StockCardWarehousePatchHttpRequest",
                "STOK_DEPO_DETAYLARI",
                [
                    Field("salesStopped", "Depoda satisa kapali", "sdp_satisdursun", "bool"),
                    Field("orderStopped", "Depoda siparise kapali", "sdp_sipdursun", "bool"),
                    Field("receivingStopped", "Depoda mal kabule kapali", "sdp_malkabuldursun", "bool"),
                    Field("isPassive", "Depoda pasif", "sdp_Pasif_fl", "bool"),
                    Field("discountDisabled", "Depoda iskonto yapilamaz", "sdp_IskontoYapilamaz", "bool"),
                    Field("resetToGlobal", "Global ayara don", "-", "bool", "Mikro kolonu degil; API bu bayrakla depo detay satirini siler.")
                ]),
            Section(
                "stock-sales-price",
                "Stok Satis Fiyati",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/stok-kartlari/{stockCode}/satis-fiyatlari/{warehouseNo}",
                "StockSalesPriceUpsertHttpRequest",
                "STOK_SATIS_FIYAT_LISTELERI",
                [
                    Field("priceListNo", "Fiyat liste no", "sfiyat_listesirano", "int"),
                    Field("paymentPlanNo", "Odeme plani no", "sfiyat_odemeplan", "int"),
                    Field("unitPointer", "Birim pointer", "sfiyat_birim_pntr", "byte"),
                    Field("price", "Fiyat", "sfiyat_fiyati", "double"),
                    Field("currencyType", "Doviz cinsi", "sfiyat_doviz", "byte"),
                    Field("changeReason", "Degisim nedeni", "sfiyat_deg_neden", "byte")
                ]),
            Section(
                "warehouse-card",
                "Depo Karti",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/depolar/{warehouseNo}",
                "WarehouseCardPatchHttpRequest",
                "DEPOLAR",
                [
                    Field("name", "Depo adi", "dep_adi", "string"),
                    Field("groupCode", "Depo grup kodu", "dep_grup_kodu", "string"),
                    Field("warehouseType", "Depo tipi", "dep_tipi", "byte"),
                    Field("shipmentAutoPriceType", "Depo sevk oto fiyat tipi", "dep_DepoSevkOtoFiyat", "byte"),
                    Field("movementType", "Hareket tipi", "dep_hareket_tipi", "byte"),
                    Field("accountingCode", "Muhasebe kodu", "dep_muh_kodu", "string"),
                    Field("responsibilityCenter", "Sorumluluk merkezi", "dep_sor_mer_kodu", "string"),
                    Field("projectCode", "Proje kodu", "dep_proje_kodu", "string"),
                    Field("special1", "Ozel kod 1", "dep_special1", "string", "En fazla 4 karakter."),
                    Field("special2", "Ozel kod 2", "dep_special2", "string", "En fazla 4 karakter."),
                    Field("special3", "Ozel kod 3", "dep_special3", "string", "En fazla 4 karakter."),
                    Field("shipmentAppliedPriceNo", "Depo sevk uygulanan fiyat no", "dep_DepoSevkUygFiyat", "int"),
                    Field("lockDate", "Kilit tarihi", "dep_KilitTarihi", "date"),
                    Field("street", "Cadde", "dep_cadde", "string"),
                    Field("neighborhood", "Mahalle", "dep_mahalle", "string"),
                    Field("avenue", "Sokak", "dep_sokak", "string"),
                    Field("quarter", "Semt", "dep_Semt", "string"),
                    Field("apartmentNo", "Apartman no", "dep_Apt_No", "string"),
                    Field("apartmentUnitNo", "Daire no", "dep_Daire_No", "string"),
                    Field("postalCode", "Posta kodu", "dep_posta_Kodu", "string"),
                    Field("district", "Ilce", "dep_Ilce", "string"),
                    Field("city", "Il", "dep_Il", "string"),
                    Field("country", "Ulke", "dep_Ulke", "string"),
                    Field("addressCode", "Adres kodu", "dep_Adres_kodu", "string"),
                    Field("latitude", "GPS enlem", "dep_gps_enlem", "double"),
                    Field("longitude", "GPS boylam", "dep_gps_boylam", "double"),
                    Field("authorizedEmail", "Yetkili e-posta", "dep_yetkili_email", "string"),
                    Field("phoneCountryCode", "Telefon ulke kodu", "dep_tel_ulke_kodu", "string"),
                    Field("phoneAreaCode", "Telefon bolge kodu", "dep_tel_bolge_kodu", "string"),
                    Field("phoneNo1", "Telefon 1", "dep_tel_no1", "string"),
                    Field("phoneNo2", "Telefon 2", "dep_tel_no2", "string"),
                    Field("faxNo", "Faks", "dep_tel_faxno", "string"),
                    Field("excludedFromInventory", "Envanter harici", "dep_envanter_harici_fl", "bool"),
                    Field("detailTrackingType", "Detay takip tipi", "dep_detay_takibi", "byte"),
                    Field("regionCode", "Bolge kodu", "dep_bolge_kodu", "string"),
                    Field("outgoingEDespatchEnabled", "Gidiste e-irsaliye", "dep_gidiste_eirsaliye_fl", "bool"),
                    Field("incomingEDespatchEnabled", "Geliste e-irsaliye", "dep_geliste_eirsaliye_fl", "bool"),
                    Field("isPassive", "Pasif", "dep_iptal", "bool"),
                    Field("isHidden", "Gizli", "dep_hidden", "bool"),
                    Field("isLocked", "Kilitli", "dep_kilitli", "bool")
                ]),
            Section(
                "customer-card",
                "Cari Karti",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/cariler/{customerCode}",
                "CustomerCardPatchHttpRequest",
                "CARI_HESAPLAR",
                [
                    Field("title1", "Unvan 1", "cari_unvan1", "string"),
                    Field("title2", "Unvan 2", "cari_unvan2", "string"),
                    Field("special1", "Ozel kod 1", "cari_special1", "string", "En fazla 4 karakter."),
                    Field("special2", "Ozel kod 2", "cari_special2", "string", "En fazla 4 karakter."),
                    Field("special3", "Ozel kod 3", "cari_special3", "string", "En fazla 4 karakter."),
                    Field("movementType", "Hareket tipi", "cari_hareket_tipi", "byte"),
                    Field("connectionType", "Baglanti tipi", "cari_baglanti_tipi", "byte"),
                    Field("purchaseStockType", "Alis stok cinsi", "cari_stok_alim_cinsi", "byte"),
                    Field("salesStockType", "Satis stok cinsi", "cari_stok_satim_cinsi", "byte"),
                    Field("accountingCode", "Muhasebe kodu", "cari_muh_kod", "string"),
                    Field("accountingCode1", "Muhasebe kodu 1", "cari_muh_kod1", "string"),
                    Field("accountingCode2", "Muhasebe kodu 2", "cari_muh_kod2", "string"),
                    Field("currencyType", "Doviz cinsi", "cari_doviz_cinsi", "byte"),
                    Field("currencyType1", "Doviz cinsi 1", "cari_doviz_cinsi1", "byte"),
                    Field("currencyType2", "Doviz cinsi 2", "cari_doviz_cinsi2", "byte"),
                    Field("taxOffice", "Vergi dairesi", "cari_vdaire_adi", "string"),
                    Field("taxOfficeNo", "Vergi daire no", "cari_vdaire_no", "string"),
                    Field("registryNo", "Sicil no", "cari_sicil_no", "string"),
                    Field("taxNo", "Vergi/TCKN no", "cari_VergiKimlikNo", "string"),
                    Field("salesPriceListNo", "Satis fiyat liste no", "cari_satis_fk", "int"),
                    Field("paymentType", "Odeme cinsi", "cari_odeme_cinsi", "byte"),
                    Field("paymentDay", "Odeme gunu", "cari_odeme_gunu", "byte"),
                    Field("paymentPlanNo", "Odeme plani no", "cari_odemeplan_no", "int"),
                    Field("optionDay", "Opsiyon gunu", "cari_opsiyon_gun", "int"),
                    Field("invoiceAddressNo", "Fatura adres no", "cari_fatura_adres_no", "int"),
                    Field("shippingAddressNo", "Sevk adres no", "cari_sevk_adres_no", "int"),
                    Field("parentCustomerCode", "Ana cari kodu", "cari_Ana_cari_kodu", "string"),
                    Field("sectorCode", "Sektor kodu", "cari_sektor_kodu", "string"),
                    Field("regionCode", "Bolge kodu", "cari_bolge_kodu", "string"),
                    Field("groupCode", "Grup kodu", "cari_grup_kodu", "string"),
                    Field("representativeCode", "Temsilci kodu", "cari_temsilci_kodu", "string"),
                    Field("isClosed", "Cari kapali", "cari_firma_acik_kapal", "bool"),
                    Field("isLocked", "Cari kilitli", "cari_cari_kilitli_flg", "bool"),
                    Field("eInvoiceEnabled", "E-fatura aktif", "cari_efatura_fl", "bool"),
                    Field("defaultEInvoiceType", "Varsayilan e-fatura tipi", "cari_def_efatura_cinsi", "byte"),
                    Field("eDespatchEnabled", "E-irsaliye aktif", "cari_eirsaliye_fl", "bool"),
                    Field("defaultEDespatchType", "Varsayilan e-irsaliye tipi", "cari_def_eirsaliye_cinsi", "byte"),
                    Field("website", "Web sitesi", "cari_wwwadresi", "string"),
                    Field("email", "E-posta", "cari_EMail", "string"),
                    Field("mobilePhone", "Cep telefonu", "cari_CepTel", "string"),
                    Field("defaultInputWarehouseNo", "Varsayilan giris depo", "cari_VarsayilanGirisDepo", "int"),
                    Field("defaultOutputWarehouseNo", "Varsayilan cikis depo", "cari_VarsayilanCikisDepo", "int"),
                    Field("kepAddress", "KEP adresi", "cari_KEP_adresi", "string"),
                    Field("reconciliationEmail", "Mutabakat e-posta", "cari_mutabakat_mail_adresi", "string"),
                    Field("mersisNo", "Mersis no", "cari_mersis_no", "string"),
                    Field("taxOfficeCode", "Vergi daire kodu", "cari_vergidairekodu", "string"),
                    Field("retailCustomer", "Perakende cari", "cari_Perakende_fl", "bool")
                ]),
            Section(
                "stock-movement-header",
                "Stok Hareket Evraki Header",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/stok-hareketleri",
                "StockMovementHeaderPatchHttpRequest",
                "STOK_HAREKETLERI",
                [
                    Field("header.movementDate", "Hareket tarihi", "sth_tarih", "date"),
                    Field("header.documentDate", "Belge tarihi", "sth_belge_tarih", "date"),
                    Field("header.goodsAcceptanceDate", "Mal kabul/sevk tarihi", "sth_malkbl_sevk_tarihi", "date"),
                    Field("header.documentNo", "Belge no", "sth_belge_no", "string"),
                    Field("header.customerCode", "Cari kodu", "sth_cari_kodu", "string"),
                    Field("header.inputWarehouseNo", "Giris depo", "sth_giris_depo_no", "int"),
                    Field("header.outputWarehouseNo", "Cikis depo", "sth_cikis_depo_no", "int"),
                    Field("header.shippingWarehouseNo", "Nakliye deposu", "sth_nakliyedeposu", "int"),
                    Field("header.description", "Aciklama", "sth_aciklama", "string"),
                    Field("header.movementGroupCode1", "Hareket grup kodu 1", "sth_HareketGrupKodu1", "string"),
                    Field("header.movementGroupCode2", "Hareket grup kodu 2", "sth_HareketGrupKodu2", "string"),
                    Field("header.movementGroupCode3", "Hareket grup kodu 3", "sth_HareketGrupKodu3", "string"),
                    Field("header.customerResponsibilityCenter", "Cari sorumluluk merkezi", "sth_cari_srm_merkezi", "string"),
                    Field("header.stockResponsibilityCenter", "Stok sorumluluk merkezi", "sth_stok_srm_merkezi", "string"),
                    Field("header.projectCode", "Proje kodu", "sth_proje_kodu", "string"),
                    Field("header.documentType", "Evrak tipi", "sth_evraktip", "byte", "Response/lookup alanidir; evrak kimligini bozmasin diye patch edilmez.", editable: false),
                    Field("header.movementKind", "Hareket cinsi", "sth_cins", "byte", "Response/lookup alanidir; patch edilmez.", editable: false),
                    Field("header.normalReturn", "Normal/iade", "sth_normal_iade", "byte", "Response/lookup alanidir; patch edilmez.", editable: false)
                ]),
            Section(
                "stock-movement-line",
                "Stok Hareket Evraki Satir",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/stok-hareketleri",
                "StockMovementLinePatchHttpRequest",
                "STOK_HAREKETLERI",
                [
                    Field("lines[].rowNo", "Satir no", "sth_satirno", "int"),
                    Field("lines[].goodsAcceptanceDate", "Mal kabul/sevk tarihi", "sth_malkbl_sevk_tarihi", "date"),
                    Field("lines[].stockCode", "Stok kodu", "sth_stok_kod", "string"),
                    Field("lines[].unitPointer", "Birim pointer", "sth_birim_pntr", "byte"),
                    Field("lines[].quantity", "Miktar", "sth_miktar", "double"),
                    Field("lines[].secondaryQuantity", "Ikinci miktar", "sth_miktar2", "double"),
                    Field("lines[].unitPrice", "Birim fiyat", "-", "double", "STOK_HAREKETLERI tablosunda direkt kolon yoktur; API response'ta amount / quantity olarak hesaplanir. Fiyat etkisi icin amount veya quantity degistirilir.", editable: false),
                    Field("lines[].amount", "Tutar", "sth_tutar", "double"),
                    Field("lines[].discount1..6", "Iskonto 1-6", "sth_iskonto1..sth_iskonto6", "double"),
                    Field("lines[].expense1..4", "Masraf 1-4", "sth_masraf1..sth_masraf4", "double"),
                    Field("lines[].expenseTaxPointer", "Masraf vergi pointer", "sth_masraf_vergi_pntr", "byte"),
                    Field("lines[].expenseTaxAmount", "Masraf vergi tutari", "sth_masraf_vergi", "double"),
                    Field("lines[].taxPointer", "Vergi pointer", "sth_vergi_pntr", "byte"),
                    Field("lines[].taxAmount", "Vergi tutari", "sth_vergi", "double"),
                    Field("lines[].netWeight", "Net agirlik", "sth_netagirlik", "double"),
                    Field("lines[].grossWeight", "Brut agirlik", "sth_brutagirlik", "double"),
                    Field("lines[].description", "Aciklama", "sth_aciklama", "string"),
                    Field("lines[].special1", "Ozel kod 1", "sth_special1", "string", "En fazla 4 karakter."),
                    Field("lines[].special2", "Ozel kod 2", "sth_special2", "string", "En fazla 4 karakter."),
                    Field("lines[].special3", "Ozel kod 3", "sth_special3", "string", "En fazla 4 karakter."),
                    Field("lines[].partyCode", "Parti kodu", "sth_parti_kodu", "string"),
                    Field("lines[].lotNo", "Lot no", "sth_lot_no", "int"),
                    Field("lines[].projectCode", "Proje kodu", "sth_proje_kodu", "string"),
                    Field("lines[].customerResponsibilityCenter", "Cari sorumluluk merkezi", "sth_cari_srm_merkezi", "string"),
                    Field("lines[].stockResponsibilityCenter", "Stok sorumluluk merkezi", "sth_stok_srm_merkezi", "string"),
                    Field("lines[].inputWarehouseNo", "Giris depo", "sth_giris_depo_no", "int"),
                    Field("lines[].outputWarehouseNo", "Cikis depo", "sth_cikis_depo_no", "int")
                ]),
            Section(
                "inventory-count-header",
                "Sayim Sonucu Header",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/sayim-sonuclari",
                "InventoryCountHeaderPatchHttpRequest",
                "SAYIM_SONUCLARI",
                [
                    Field("header.documentDate", "Sayim tarihi", "sym_tarihi", "date"),
                    Field("header.warehouseNo", "Depo", "sym_depono", "int"),
                    Field("header.name", "Sayim adi/notu", "sym_parti_kodu", "string")
                ]),
            Section(
                "inventory-count-line",
                "Sayim Sonucu Satir",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/sayim-sonuclari",
                "InventoryCountLinePatchHttpRequest",
                "SAYIM_SONUCLARI",
                [
                    Field("lines[].countGuid", "Sayim satir GUID", "sym_Guid", "guid", "Satir eslestirme anahtaridir; patch edilmez.", editable: false),
                    Field("lines[].rowNo", "Satir no", "sym_satirno", "int"),
                    Field("lines[].stockCode", "Stok kodu", "sym_Stokkodu", "string"),
                    Field("lines[].barcode", "Barkod", "sym_barkod", "string"),
                    Field("lines[].unitPointer", "Birim pointer", "sym_birim_pntr", "byte"),
                    Field("lines[].quantity1", "Sayim miktari 1", "sym_miktar1", "double"),
                    Field("lines[].quantity2", "Sayim miktari 2", "sym_miktar2", "double"),
                    Field("lines[].quantity3", "Sayim miktari 3", "sym_miktar3", "double"),
                    Field("lines[].quantity4", "Sayim miktari 4", "sym_miktar4", "double"),
                    Field("lines[].quantity5", "Sayim miktari 5", "sym_miktar5", "double"),
                    Field("lines[].rayonCode", "Reyon kodu", "sym_reyonkodu", "string", "En fazla 4 karakter."),
                    Field("lines[].corridorCode", "Koridor kodu", "sym_koridorkodu", "string", "En fazla 4 karakter."),
                    Field("lines[].shelfCode", "Raf kodu", "sym_rafkodu", "string", "En fazla 4 karakter."),
                    Field("lines[].partyCode", "Parti kodu", "sym_parti_kodu", "string"),
                    Field("lines[].lotNo", "Lot no", "sym_lot_no", "int"),
                    Field("lines[].serialNo", "Seri/iz no", "sym_serino", "string"),
                    Field("lines[].special1", "Ozel kod 1", "sym_special1", "string", "En fazla 4 karakter."),
                    Field("lines[].special2", "Ozel kod 2", "sym_special2", "string", "En fazla 4 karakter."),
                    Field("lines[].special3", "Ozel kod 3", "sym_special3", "string", "En fazla 4 karakter.")
                ]),
            Section(
                "customer-movement-line",
                "Cari Hareket Evraki Satir",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/cari-hareketleri",
                "CustomerMovementLinePatchHttpRequest",
                "CARI_HESAP_HAREKETLERI",
                [
                    Field("lines[].rowNo", "Satir no", "cha_satir_no", "int"),
                    Field("lines[].customerCode", "Cari kodu", "cha_kod", "string"),
                    Field("lines[].turnoverCustomerCode", "Ciro cari kodu", "cha_ciro_cari_kodu", "string"),
                    Field("lines[].quantity", "Miktar", "cha_miktari", "double"),
                    Field("lines[].amount", "Meblag", "cha_meblag", "double"),
                    Field("lines[].subAmount", "Ara toplam", "cha_aratoplam", "double"),
                    Field("lines[].dueDay", "Vade gunu", "cha_vade", "int"),
                    Field("lines[].discount1..6", "Iskonto 1-6", "cha_ft_iskonto1..cha_ft_iskonto6", "double"),
                    Field("lines[].expense1..4", "Masraf 1-4", "cha_ft_masraf1..cha_ft_masraf4", "double"),
                    Field("lines[].tax1..5", "Vergi 1-5", "cha_vergi1..cha_vergi5", "double"),
                    Field("lines[].description", "Aciklama", "cha_aciklama", "string"),
                    Field("lines[].special1", "Ozel kod 1", "cha_special1", "string", "En fazla 4 karakter."),
                    Field("lines[].special2", "Ozel kod 2", "cha_special2", "string", "En fazla 4 karakter."),
                    Field("lines[].special3", "Ozel kod 3", "cha_special3", "string", "En fazla 4 karakter."),
                    Field("lines[].sellerCode", "Satici kodu", "cha_satici_kodu", "string"),
                    Field("lines[].projectCode", "Proje kodu", "cha_projekodu", "string"),
                    Field("lines[].responsibilityCenter", "Sorumluluk merkezi", "cha_srmrkkodu", "string")
                ]),
            Section(
                "customer-movement-header",
                "Cari Hareket Evraki Header",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/cari-hareketleri",
                "CustomerMovementHeaderPatchHttpRequest",
                "CARI_HESAP_HAREKETLERI",
                [
                    Field("header.movementDate", "Hareket tarihi", "cha_tarihi", "date"),
                    Field("header.documentDate", "Belge tarihi", "cha_belge_tarih", "date"),
                    Field("header.documentNo", "Belge no", "cha_belge_no", "string"),
                    Field("header.customerCode", "Cari kodu", "cha_kod", "string"),
                    Field("header.turnoverCustomerCode", "Ciro cari kodu", "cha_ciro_cari_kodu", "string"),
                    Field("header.description", "Aciklama", "cha_aciklama", "string"),
                    Field("header.sellerCode", "Satici kodu", "cha_satici_kodu", "string"),
                    Field("header.projectCode", "Proje kodu", "cha_projekodu", "string"),
                    Field("header.responsibilityCenter", "Sorumluluk merkezi", "cha_srmrkkodu", "string"),
                    Field("header.documentType", "Evrak tipi", "cha_evrak_tip", "byte", "Response/lookup alanidir; patch edilmez.", editable: false),
                    Field("header.movementKind", "Hareket cinsi", "cha_cinsi", "byte", "Response/lookup alanidir; patch edilmez.", editable: false),
                    Field("header.normalReturn", "Normal/iade", "cha_normal_Iade", "byte", "Response/lookup alanidir; patch edilmez.", editable: false)
                ]),
            Section(
                "company-order-header",
                "Firma Siparisi Header",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/firma-siparisleri",
                "CompanyOrderHeaderPatchHttpRequest",
                "SIPARISLER",
                [
                    Field("header.orderDate", "Siparis tarihi", "sip_tarih", "date"),
                    Field("header.deliveryDate", "Teslim tarihi", "sip_teslim_tarih", "date"),
                    Field("header.documentDate", "Belge tarihi", "sip_belge_tarih", "date"),
                    Field("header.documentNo", "Belge no", "sip_belgeno", "string"),
                    Field("header.customerCode", "Cari kodu", "sip_musteri_kod", "string"),
                    Field("header.warehouseNo", "Depo no", "sip_depono", "int"),
                    Field("header.sellerCode", "Satici kodu", "sip_satici_kod", "string"),
                    Field("header.description1", "Aciklama 1", "sip_aciklama", "string"),
                    Field("header.description2", "Aciklama 2", "sip_aciklama2", "string"),
                    Field("header.deliveryType", "Teslim turu", "sip_teslimturu", "string"),
                    Field("header.addressNo", "Adres no", "sip_adresno", "int"),
                    Field("header.currencyType", "Doviz cinsi", "sip_doviz_cinsi", "byte"),
                    Field("header.currencyRate", "Doviz kuru", "sip_doviz_kuru", "double"),
                    Field("header.alternativeCurrencyRate", "Alternatif doviz kuru", "sip_alt_doviz_kuru", "double"),
                    Field("header.canBeCalled", "Cagrilabilir", "sip_cagrilabilir_fl", "bool"),
                    Field("header.isClosed", "Kapali", "sip_kapat_fl", "bool"),
                    Field("header.closeReasonCode", "Kapama neden kodu", "sip_kapatmanedenkod", "string"),
                    Field("header.projectCode", "Proje kodu", "sip_projekodu", "string"),
                    Field("header.customerResponsibilityCenter", "Cari sorumluluk merkezi", "sip_cari_sormerk", "string"),
                    Field("header.stockResponsibilityCenter", "Stok sorumluluk merkezi", "sip_stok_sormerk", "string"),
                    Field("header.orderType", "Siparis tipi", "sip_tip", "byte", "Response/lookup alanidir; evrak kimligini bozmasin diye patch edilmez.", editable: false),
                    Field("header.orderKind", "Siparis cinsi", "sip_cins", "byte", "Response/lookup alanidir; patch edilmez.", editable: false)
                ]),
            Section(
                "company-order-line",
                "Firma Siparisi Satir",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/firma-siparisleri",
                "CompanyOrderLinePatchHttpRequest",
                "SIPARISLER",
                [
                    Field("lines[].rowNo", "Satir no", "sip_satirno", "int"),
                    Field("lines[].deliveryDate", "Teslim tarihi", "sip_teslim_tarih", "date"),
                    Field("lines[].stockCode", "Stok kodu", "sip_stok_kod", "string"),
                    Field("lines[].unitPointer", "Birim pointer", "sip_birim_pntr", "byte"),
                    Field("lines[].quantity", "Miktar", "sip_miktar", "double"),
                    Field("lines[].deliveredQuantity", "Teslim miktari", "sip_teslim_miktar", "double"),
                    Field("lines[].unitPrice", "Birim fiyat", "sip_b_fiyat", "double"),
                    Field("lines[].amount", "Tutar", "sip_tutar", "double"),
                    Field("lines[].priceListNo", "Fiyat liste no", "sip_fiyat_liste_no", "int"),
                    Field("lines[].validUntil", "Gecerlilik tarihi", "sip_gecerlilik_tarihi", "date"),
                    Field("lines[].reservedQuantity", "Rezervasyon miktari", "sip_rezervasyon_miktari", "double"),
                    Field("lines[].deliveredFromReservation", "Rezerveden teslim edilen", "sip_rezerveden_teslim_edilen", "double"),
                    Field("lines[].discount1..6", "Iskonto 1-6", "sip_iskonto_1..sip_iskonto_6", "double"),
                    Field("lines[].expense1..4", "Masraf 1-4", "sip_masraf_1..sip_masraf_4", "double"),
                    Field("lines[].taxPointer", "Vergi pointer", "sip_vergi_pntr", "byte"),
                    Field("lines[].taxAmount", "Vergi tutari", "sip_vergi", "double"),
                    Field("lines[].description1", "Aciklama 1", "sip_aciklama", "string"),
                    Field("lines[].description2", "Aciklama 2", "sip_aciklama2", "string"),
                    Field("lines[].special1", "Ozel kod 1", "sip_special1", "string", "En fazla 4 karakter."),
                    Field("lines[].special2", "Ozel kod 2", "sip_special2", "string", "En fazla 4 karakter."),
                    Field("lines[].special3", "Ozel kod 3", "sip_special3", "string", "En fazla 4 karakter."),
                    Field("lines[].packageCode", "Paket kodu", "sip_paket_kod", "string"),
                    Field("lines[].partyCode", "Parti kodu", "sip_parti_kodu", "string"),
                    Field("lines[].lotNo", "Lot no", "sip_lot_no", "int"),
                    Field("lines[].projectCode", "Proje kodu", "sip_projekodu", "string"),
                    Field("lines[].customerResponsibilityCenter", "Cari sorumluluk merkezi", "sip_cari_sormerk", "string"),
                    Field("lines[].stockResponsibilityCenter", "Stok sorumluluk merkezi", "sip_stok_sormerk", "string"),
                    Field("lines[].canBeCalled", "Cagrilabilir", "sip_cagrilabilir_fl", "bool"),
                    Field("lines[].isClosed", "Kapali", "sip_kapat_fl", "bool"),
                    Field("lines[].closeReasonCode", "Kapama neden kodu", "sip_kapatmanedenkod", "string")
                ]),
            Section(
                "warehouse-order-header",
                "Depo Siparisi Header",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/depo-siparisleri",
                "WarehouseOrderHeaderPatchHttpRequest",
                "DEPOLAR_ARASI_SIPARISLER",
                [
                    Field("header.orderDate", "Siparis tarihi", "ssip_tarih", "date"),
                    Field("header.deliveryDate", "Teslim tarihi", "ssip_teslim_tarih", "date"),
                    Field("header.documentDate", "Belge tarihi", "ssip_belge_tarih", "date"),
                    Field("header.documentNo", "Belge no", "ssip_belgeno", "string"),
                    Field("header.inWarehouseNo", "Giris depo", "ssip_girdepo", "int"),
                    Field("header.outWarehouseNo", "Cikis depo", "ssip_cikdepo", "int"),
                    Field("header.description", "Aciklama", "ssip_aciklama", "string"),
                    Field("header.isClosed", "Kapali", "ssip_kapat_fl", "bool"),
                    Field("header.closeReasonCode", "Kapama neden kodu", "ssip_kapatmanedenkod", "string"),
                    Field("header.projectCode", "Proje kodu", "ssip_projekodu", "string"),
                    Field("header.responsibilityCenter", "Sorumluluk merkezi", "ssip_sormerkezi", "string")
                ]),
            Section(
                "warehouse-order-line",
                "Depo Siparisi Satir",
                "PUT /api/duzeltme-islemleri/mikro-evrak-duzenleme/depo-siparisleri",
                "WarehouseOrderLinePatchHttpRequest",
                "DEPOLAR_ARASI_SIPARISLER",
                [
                    Field("lines[].rowNo", "Satir no", "ssip_satirno", "int"),
                    Field("lines[].deliveryDate", "Teslim tarihi", "ssip_teslim_tarih", "date"),
                    Field("lines[].stockCode", "Stok kodu", "ssip_stok_kod", "string"),
                    Field("lines[].unitPointer", "Birim pointer", "ssip_birim_pntr", "byte"),
                    Field("lines[].quantity", "Miktar", "ssip_miktar", "double"),
                    Field("lines[].deliveredQuantity", "Teslim miktari", "ssip_teslim_miktar", "double"),
                    Field("lines[].unitPrice", "Birim fiyat", "ssip_b_fiyat", "double"),
                    Field("lines[].amount", "Tutar", "ssip_tutar", "double"),
                    Field("lines[].description", "Aciklama", "ssip_aciklama", "string"),
                    Field("lines[].priceListNo", "Fiyat liste no", "ssip_fiyat_liste_no", "int"),
                    Field("lines[].validUntil", "Gecerlilik tarihi", "ssip_gecerlilik_tarihi", "date"),
                    Field("lines[].reservedQuantity", "Rezervasyon miktari", "ssip_rezervasyon_miktari", "double"),
                    Field("lines[].deliveredFromReservation", "Rezerveden teslim edilen", "ssip_rezerveden_teslim_edilen", "double"),
                    Field("lines[].special1", "Ozel kod 1", "ssip_special1", "string", "En fazla 4 karakter."),
                    Field("lines[].special2", "Ozel kod 2", "ssip_special2", "string", "En fazla 4 karakter."),
                    Field("lines[].special3", "Ozel kod 3", "ssip_special3", "string", "En fazla 4 karakter."),
                    Field("lines[].inWarehouseNo", "Giris depo", "ssip_girdepo", "int"),
                    Field("lines[].outWarehouseNo", "Cikis depo", "ssip_cikdepo", "int"),
                    Field("lines[].isClosed", "Kapali", "ssip_kapat_fl", "bool"),
                    Field("lines[].closeReasonCode", "Kapama neden kodu", "ssip_kapatmanedenkod", "string"),
                    Field("lines[].packageCode", "Paket kodu", "ssip_paket_kod", "string"),
                    Field("lines[].projectCode", "Proje kodu", "ssip_projekodu", "string"),
                    Field("lines[].responsibilityCenter", "Sorumluluk merkezi", "ssip_sormerkezi", "string")
                ])
        ]);

    private static MikroDocumentFieldMappingDto Field(
        string apiField,
        string displayName,
        string column,
        string valueType,
        string description = "",
        bool editable = true) =>
        new(
            apiField,
            displayName,
            ResolveScope(apiField),
            valueType,
            "-",
            column,
            editable,
            description);

    private static MikroDocumentFieldSectionDto Section(
        string code,
        string title,
        string endpoint,
        string requestModel,
        string table,
        MikroDocumentFieldMappingDto[] fields) =>
        new(
            code,
            title,
            endpoint,
            requestModel,
            fields.Select(field => field with { MikroTable = table }).ToArray());

    private static string ResolveScope(string apiField)
    {
        if (apiField.StartsWith("header.", StringComparison.Ordinal))
        {
            return "header";
        }

        if (apiField.StartsWith("lines[].", StringComparison.Ordinal))
        {
            return "line";
        }

        return "body";
    }
}
