namespace FurpaMerkezApi.Application.Modules.AramaIslemleri.SearchProducts;

public sealed record ProductLookupItemDto(
    int WarehouseNo,
    string Barcode,
    string StockCode,
    string StockName,
    double Price,
    int PriceTypeCode,
    string UnitName,
    double UnitMultiplier,
    string SecondaryUnitName,
    double SecondaryUnitMultiplier,
    int? SalesBlockCode,
    int? OrderBlockCode,
    int? GoodsAcceptanceBlockCode,
    bool IsSalesBlocked,
    bool IsOrderBlocked,
    bool IsGoodsAcceptanceBlocked,
    string ProductManagerCode,
    string? RequestedBarcode = null,
    string? LookupBarcode = null,
    bool IsVariableWeightBarcode = false,
    double? EmbeddedQuantity = null,
    string? EmbeddedQuantityUnit = null,
    bool? IsBarcodeCheckDigitValid = null,
    double? PurchasePrice = null,
    double? PurchaseGrossPrice = null,
    string? PurchasePriceSource = null,
    string? PurchaseSupplierCode = null);
