//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler hatalı davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("", ClrNamespace="")]

namespace FurpaMerkezApi.Infrastructure.Modules.EntegrasyonIslemleri.AxataSenkronizasyonu.ServiceReferences.Ext
{



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="IntegrationTable", Namespace="")]
public partial class IntegrationTable : object
{
    
    private string TableNameField;
    
    private string UpdateFieldField;
    
    private string UpdateValueField;
    
    private string IDFieldField;
    
    private IDList IDValuesField;
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string TableName
    {
        get
        {
            return this.TableNameField;
        }
        set
        {
            this.TableNameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string UpdateField
    {
        get
        {
            return this.UpdateFieldField;
        }
        set
        {
            this.UpdateFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
    public string UpdateValue
    {
        get
        {
            return this.UpdateValueField;
        }
        set
        {
            this.UpdateValueField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
    public string IDField
    {
        get
        {
            return this.IDFieldField;
        }
        set
        {
            this.IDFieldField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
    public IDList IDValues
    {
        get
        {
            return this.IDValuesField;
        }
        set
        {
            this.IDValuesField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.CollectionDataContractAttribute(Name="IDList", Namespace="", ItemName="IDValue")]
public class IDList : System.Collections.Generic.List<string>
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="")]
public partial class ProcessResult : object
{
    
    private int LogStateField;
    
    private string LogMessageField;
    
    private long EntityIDField;
    
    private string EntityCompanyField;
    
    private string EntityCodeField;
    
    private string EntitySubCodeField;
    
    private string HeaderExt1Field;
    
    private string HeaderExt2Field;
    
    private string HeaderExt3Field;
    
    private ResultItem[] ResultItemsField;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int LogState
    {
        get
        {
            return this.LogStateField;
        }
        set
        {
            this.LogStateField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public string LogMessage
    {
        get
        {
            return this.LogMessageField;
        }
        set
        {
            this.LogMessageField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public long EntityID
    {
        get
        {
            return this.EntityIDField;
        }
        set
        {
            this.EntityIDField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public string EntityCompany
    {
        get
        {
            return this.EntityCompanyField;
        }
        set
        {
            this.EntityCompanyField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    public string EntityCode
    {
        get
        {
            return this.EntityCodeField;
        }
        set
        {
            this.EntityCodeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    public string EntitySubCode
    {
        get
        {
            return this.EntitySubCodeField;
        }
        set
        {
            this.EntitySubCodeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
    public string HeaderExt1
    {
        get
        {
            return this.HeaderExt1Field;
        }
        set
        {
            this.HeaderExt1Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
    public string HeaderExt2
    {
        get
        {
            return this.HeaderExt2Field;
        }
        set
        {
            this.HeaderExt2Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
    public string HeaderExt3
    {
        get
        {
            return this.HeaderExt3Field;
        }
        set
        {
            this.HeaderExt3Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
    public ResultItem[] ResultItems
    {
        get
        {
            return this.ResultItemsField;
        }
        set
        {
            this.ResultItemsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ResultItem", Namespace="")]
public partial class ResultItem : object
{
    
    private string Attribute1Field;
    
    private string Attribute2Field;
    
    private string Attribute3Field;
    
    private string Attribute4Field;
    
    private string Attribute5Field;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Attribute1
    {
        get
        {
            return this.Attribute1Field;
        }
        set
        {
            this.Attribute1Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Attribute2
    {
        get
        {
            return this.Attribute2Field;
        }
        set
        {
            this.Attribute2Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Attribute3
    {
        get
        {
            return this.Attribute3Field;
        }
        set
        {
            this.Attribute3Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Attribute4
    {
        get
        {
            return this.Attribute4Field;
        }
        set
        {
            this.Attribute4Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Attribute5
    {
        get
        {
            return this.Attribute5Field;
        }
        set
        {
            this.Attribute5Field = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ENT053", Namespace="")]
public partial class ENT053 : object
{
    
    private string S53SIRKODField;
    
    private string S53SIPNOField;
    
    private string S53TAKIPNOField;
    
    private string S53TAKIP_SERIField;
    
    private string S53DRM_KODField;
    
    private string S53DRM_ACIKLAMAField;
    
    private string S53TESLIM_ADSOYADField;
    
    private string S53TESALAN_ADSOYADField;
    
    private string S53TESLIM_ACIKLAMAField;
    
    private System.Nullable<System.DateTime> S53TESLIM_TARIHIField;
    
    private System.Nullable<System.DateTime> S53HEDEF_TARIHField;
    
    private string S53HKODField;
    
    private int S53SIPTIPIField;
    
    private System.Nullable<System.DateTime> S53ATF_TARIHField;
    
    private decimal S53KOLINOField;
    
    private System.Nullable<System.DateTime> S53YUKLEME_TARIHIField;
    
    private string S53PLAKAField;
    
    private string S53SURUCUADIField;
    
    private string S53SURUCUTELField;
    
    private string S53URLField;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string S53SIRKOD
    {
        get
        {
            return this.S53SIRKODField;
        }
        set
        {
            this.S53SIRKODField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public string S53SIPNO
    {
        get
        {
            return this.S53SIPNOField;
        }
        set
        {
            this.S53SIPNOField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public string S53TAKIPNO
    {
        get
        {
            return this.S53TAKIPNOField;
        }
        set
        {
            this.S53TAKIPNOField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public string S53TAKIP_SERI
    {
        get
        {
            return this.S53TAKIP_SERIField;
        }
        set
        {
            this.S53TAKIP_SERIField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    public string S53DRM_KOD
    {
        get
        {
            return this.S53DRM_KODField;
        }
        set
        {
            this.S53DRM_KODField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    public string S53DRM_ACIKLAMA
    {
        get
        {
            return this.S53DRM_ACIKLAMAField;
        }
        set
        {
            this.S53DRM_ACIKLAMAField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
    public string S53TESLIM_ADSOYAD
    {
        get
        {
            return this.S53TESLIM_ADSOYADField;
        }
        set
        {
            this.S53TESLIM_ADSOYADField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
    public string S53TESALAN_ADSOYAD
    {
        get
        {
            return this.S53TESALAN_ADSOYADField;
        }
        set
        {
            this.S53TESALAN_ADSOYADField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
    public string S53TESLIM_ACIKLAMA
    {
        get
        {
            return this.S53TESLIM_ACIKLAMAField;
        }
        set
        {
            this.S53TESLIM_ACIKLAMAField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
    public System.Nullable<System.DateTime> S53TESLIM_TARIHI
    {
        get
        {
            return this.S53TESLIM_TARIHIField;
        }
        set
        {
            this.S53TESLIM_TARIHIField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
    public System.Nullable<System.DateTime> S53HEDEF_TARIH
    {
        get
        {
            return this.S53HEDEF_TARIHField;
        }
        set
        {
            this.S53HEDEF_TARIHField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
    public string S53HKOD
    {
        get
        {
            return this.S53HKODField;
        }
        set
        {
            this.S53HKODField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
    public int S53SIPTIPI
    {
        get
        {
            return this.S53SIPTIPIField;
        }
        set
        {
            this.S53SIPTIPIField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
    public System.Nullable<System.DateTime> S53ATF_TARIH
    {
        get
        {
            return this.S53ATF_TARIHField;
        }
        set
        {
            this.S53ATF_TARIHField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
    public decimal S53KOLINO
    {
        get
        {
            return this.S53KOLINOField;
        }
        set
        {
            this.S53KOLINOField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
    public System.Nullable<System.DateTime> S53YUKLEME_TARIHI
    {
        get
        {
            return this.S53YUKLEME_TARIHIField;
        }
        set
        {
            this.S53YUKLEME_TARIHIField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
    public string S53PLAKA
    {
        get
        {
            return this.S53PLAKAField;
        }
        set
        {
            this.S53PLAKAField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
    public string S53SURUCUADI
    {
        get
        {
            return this.S53SURUCUADIField;
        }
        set
        {
            this.S53SURUCUADIField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
    public string S53SURUCUTEL
    {
        get
        {
            return this.S53SURUCUTELField;
        }
        set
        {
            this.S53SURUCUTELField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
    public string S53URL
    {
        get
        {
            return this.S53URLField;
        }
        set
        {
            this.S53URLField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="DeliveryCancel", Namespace="")]
public partial class DeliveryCancel : object
{
    
    private string CompanyCodeField;
    
    private string SiparisNoField;
    
    private string YuklemeNoField;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string CompanyCode
    {
        get
        {
            return this.CompanyCodeField;
        }
        set
        {
            this.CompanyCodeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string SiparisNo
    {
        get
        {
            return this.SiparisNoField;
        }
        set
        {
            this.SiparisNoField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string YuklemeNo
    {
        get
        {
            return this.YuklemeNoField;
        }
        set
        {
            this.YuklemeNoField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Field", Namespace="")]
public partial class Field : object
{
    
    private string NameField;
    
    private INList INValuesField;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
    public INList INValues
    {
        get
        {
            return this.INValuesField;
        }
        set
        {
            this.INValuesField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.CollectionDataContractAttribute(Name="INList", Namespace="", ItemName="INValue")]
public class INList : System.Collections.Generic.List<string>
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Row", Namespace="")]
public partial class Row : object
{
    
    private Column[] ColumnsField;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public Column[] Columns
    {
        get
        {
            return this.ColumnsField;
        }
        set
        {
            this.ColumnsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Column", Namespace="")]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(IntegrationTable))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(IDList))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(ProcessResult[]))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(ProcessResult))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(ResultItem[]))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(ResultItem))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(ENT053[]))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(ENT053))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(DeliveryCancel[]))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(DeliveryCancel))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(Field[]))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(Field))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(INList))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(Row[]))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(Row))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(Column[]))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(CT_ENT_ULUS_SAS[]))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(CT_ENT_ULUS_SAS))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(ATFPaletBlokeCoz))]
[System.Runtime.Serialization.KnownTypeAttribute(typeof(ATFPaletBlokeCoz[]))]
public partial class Column : object
{
    
    private string NameField;
    
    private object ValueField;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name
    {
        get
        {
            return this.NameField;
        }
        set
        {
            this.NameField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public object Value
    {
        get
        {
            return this.ValueField;
        }
        set
        {
            this.ValueField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="CT_ENT_ULUS_SAS", Namespace="")]
public partial class CT_ENT_ULUS_SAS : object
{
    
    private System.Nullable<byte> CT_STATUField;
    
    private string CT_SIRKETField;
    
    private string CT_ORDERNOField;
    
    private System.Nullable<long> CT_KOLINOField;
    
    private string CT_SASNOField;
    
    private System.Nullable<System.DateTime> CT_CRDATEField;
    
    private System.Nullable<System.DateTime> CT_UPDDATEField;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.Nullable<byte> CT_STATU
    {
        get
        {
            return this.CT_STATUField;
        }
        set
        {
            this.CT_STATUField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
    public string CT_SIRKET
    {
        get
        {
            return this.CT_SIRKETField;
        }
        set
        {
            this.CT_SIRKETField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public string CT_ORDERNO
    {
        get
        {
            return this.CT_ORDERNOField;
        }
        set
        {
            this.CT_ORDERNOField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public System.Nullable<long> CT_KOLINO
    {
        get
        {
            return this.CT_KOLINOField;
        }
        set
        {
            this.CT_KOLINOField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
    public string CT_SASNO
    {
        get
        {
            return this.CT_SASNOField;
        }
        set
        {
            this.CT_SASNOField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
    public System.Nullable<System.DateTime> CT_CRDATE
    {
        get
        {
            return this.CT_CRDATEField;
        }
        set
        {
            this.CT_CRDATEField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
    public System.Nullable<System.DateTime> CT_UPDDATE
    {
        get
        {
            return this.CT_UPDDATEField;
        }
        set
        {
            this.CT_UPDDATEField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="ATFPaletBlokeCoz", Namespace="")]
public partial class ATFPaletBlokeCoz : object
{
    
    private string CompanyCodeField;
    
    private string WarehouseCodeField;
    
    private string ATFLineNoField;
    
    private System.Nullable<long> ATFNoField;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string CompanyCode
    {
        get
        {
            return this.CompanyCodeField;
        }
        set
        {
            this.CompanyCodeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string WarehouseCode
    {
        get
        {
            return this.WarehouseCodeField;
        }
        set
        {
            this.WarehouseCodeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
    public string ATFLineNo
    {
        get
        {
            return this.ATFLineNoField;
        }
        set
        {
            this.ATFLineNoField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public System.Nullable<long> ATFNo
    {
        get
        {
            return this.ATFNoField;
        }
        set
        {
            this.ATFNoField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAxataServicePoolEXT")]
public interface IAxataServicePoolEXT
{
    
    // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAxataServicePoolEXT/updIntegrationTable", ReplyAction="http://tempuri.org/IAxataServicePoolEXT/updIntegrationTableResponse")]
    System.Threading.Tasks.Task<updIntegrationTable_Res> updIntegrationTableAsync(updIntegrationTable_Req request);
    
    // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAxataServicePoolEXT/addDeliveryStatus", ReplyAction="http://tempuri.org/IAxataServicePoolEXT/addDeliveryStatusResponse")]
    System.Threading.Tasks.Task<getDeliveryStatus_Res> addDeliveryStatusAsync(getDeliveryStatus_Req request);
    
    // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAxataServicePoolEXT/addDeliveryCancel", ReplyAction="http://tempuri.org/IAxataServicePoolEXT/addDeliveryCancelResponse")]
    System.Threading.Tasks.Task<getDeliveryCancel_Res> addDeliveryCancelAsync(getDeliveryCancel_Req request);
    
    // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAxataServicePoolEXT/getViewData", ReplyAction="http://tempuri.org/IAxataServicePoolEXT/getViewDataResponse")]
    System.Threading.Tasks.Task<getViewData_Res> getViewDataAsync(getViewData_Req request);
    
    // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAxataServicePoolEXT/addUlusSAS", ReplyAction="http://tempuri.org/IAxataServicePoolEXT/addUlusSASResponse")]
    System.Threading.Tasks.Task<addUlusSAS_Res> addUlusSASAsync(addUlusSAS_Req request);
    
    // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAxataServicePoolEXT/addATFPaletBlokeCoz", ReplyAction="http://tempuri.org/IAxataServicePoolEXT/addATFPaletBlokeCozResponse")]
    System.Threading.Tasks.Task<addATFPaletBlokeCoz_Res> addATFPaletBlokeCozAsync(addATFPaletBlokeCoz_Req request);
    
    // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAxataServicePoolEXT/addATFPaletBlokeCozList", ReplyAction="http://tempuri.org/IAxataServicePoolEXT/addATFPaletBlokeCozListResponse")]
    System.Threading.Tasks.Task<addATFPaletBlokeCozList_Res> addATFPaletBlokeCozListAsync(addATFPaletBlokeCozList_Req request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class updIntegrationTable_Req
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axatawms", Order=2)]
    public IntegrationTable Table;
    
    public updIntegrationTable_Req()
    {
    }
    
    public updIntegrationTable_Req(string username, string password, IntegrationTable Table)
    {
        this.username = username;
        this.password = password;
        this.Table = Table;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class updIntegrationTable_Res
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int state;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string message;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public ProcessResult[] processResult;
    
    public updIntegrationTable_Res()
    {
    }
    
    public updIntegrationTable_Res(int state, string message, ProcessResult[] processResult)
    {
        this.state = state;
        this.message = message;
        this.processResult = processResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getDeliveryStatus_Req
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axatawms", Order=2)]
    public ENT053[] ENT053_List;
    
    public getDeliveryStatus_Req()
    {
    }
    
    public getDeliveryStatus_Req(string username, string password, ENT053[] ENT053_List)
    {
        this.username = username;
        this.password = password;
        this.ENT053_List = ENT053_List;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getDeliveryStatus_Res
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int state;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string message;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public ProcessResult[] processResult;
    
    public getDeliveryStatus_Res()
    {
    }
    
    public getDeliveryStatus_Res(int state, string message, ProcessResult[] processResult)
    {
        this.state = state;
        this.message = message;
        this.processResult = processResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getDeliveryCancel_Req
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axatawms", Order=2)]
    public DeliveryCancel[] deliveryCancelList;
    
    public getDeliveryCancel_Req()
    {
    }
    
    public getDeliveryCancel_Req(string username, string password, DeliveryCancel[] deliveryCancelList)
    {
        this.username = username;
        this.password = password;
        this.deliveryCancelList = deliveryCancelList;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getDeliveryCancel_Res
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int state;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string message;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public ProcessResult[] processResult;
    
    public getDeliveryCancel_Res()
    {
    }
    
    public getDeliveryCancel_Res(int state, string message, ProcessResult[] processResult)
    {
        this.state = state;
        this.message = message;
        this.processResult = processResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getViewData_Req
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ViewName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public Field[] ViewQuery;
    
    public getViewData_Req()
    {
    }
    
    public getViewData_Req(string username, string password, string ViewName, Field[] ViewQuery)
    {
        this.username = username;
        this.password = password;
        this.ViewName = ViewName;
        this.ViewQuery = ViewQuery;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getViewData_Res
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int state;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string message;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string ViewName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public long ViewRowCount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public Row[] ViewData;
    
    public getViewData_Res()
    {
    }
    
    public getViewData_Res(int state, string message, string ViewName, long ViewRowCount, Row[] ViewData)
    {
        this.state = state;
        this.message = message;
        this.ViewName = ViewName;
        this.ViewRowCount = ViewRowCount;
        this.ViewData = ViewData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class addUlusSAS_Req
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axatawms", Order=2)]
    public CT_ENT_ULUS_SAS[] UlusSASList;
    
    public addUlusSAS_Req()
    {
    }
    
    public addUlusSAS_Req(string username, string password, CT_ENT_ULUS_SAS[] UlusSASList)
    {
        this.username = username;
        this.password = password;
        this.UlusSASList = UlusSASList;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class addUlusSAS_Res
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int state;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string message;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public ProcessResult[] processResult;
    
    public addUlusSAS_Res()
    {
    }
    
    public addUlusSAS_Res(int state, string message, ProcessResult[] processResult)
    {
        this.state = state;
        this.message = message;
        this.processResult = processResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class addATFPaletBlokeCoz_Req
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axatawms", Order=2)]
    public ATFPaletBlokeCoz atfPaletBlokeCozQuery;
    
    public addATFPaletBlokeCoz_Req()
    {
    }
    
    public addATFPaletBlokeCoz_Req(string username, string password, ATFPaletBlokeCoz atfPaletBlokeCozQuery)
    {
        this.username = username;
        this.password = password;
        this.atfPaletBlokeCozQuery = atfPaletBlokeCozQuery;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class addATFPaletBlokeCoz_Res
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int state;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string message;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public ProcessResult[] processResult;
    
    public addATFPaletBlokeCoz_Res()
    {
    }
    
    public addATFPaletBlokeCoz_Res(int state, string message, ProcessResult[] processResult)
    {
        this.state = state;
        this.message = message;
        this.processResult = processResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class addATFPaletBlokeCozList_Req
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string username;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string password;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://axatawms", Order=2)]
    public ATFPaletBlokeCoz[] ATFPaletBlokeCozList;
    
    public addATFPaletBlokeCozList_Req()
    {
    }
    
    public addATFPaletBlokeCozList_Req(string username, string password, ATFPaletBlokeCoz[] ATFPaletBlokeCozList)
    {
        this.username = username;
        this.password = password;
        this.ATFPaletBlokeCozList = ATFPaletBlokeCozList;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class addATFPaletBlokeCozList_Res
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int state;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string message;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public ProcessResult[] processResultList;
    
    public addATFPaletBlokeCozList_Res()
    {
    }
    
    public addATFPaletBlokeCozList_Res(int state, string message, ProcessResult[] processResultList)
    {
        this.state = state;
        this.message = message;
        this.processResultList = processResultList;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface IAxataServicePoolEXTChannel : IAxataServicePoolEXT, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class AxataServicePoolEXTClient : System.ServiceModel.ClientBase<IAxataServicePoolEXT>, IAxataServicePoolEXT
{
    
    /// <summary>
    /// Hizmet uç noktasını yapılandırmak için bu kısmi metodu uygulayın.
    /// </summary>
    /// <param name="serviceEndpoint">Yapılandırılacak uç nokta</param>
    /// <param name="clientCredentials">İstemci kimlik bilgileri</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public AxataServicePoolEXTClient() : 
            base(AxataServicePoolEXTClient.GetDefaultBinding(), AxataServicePoolEXTClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAxataServicePoolEXT.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public AxataServicePoolEXTClient(EndpointConfiguration endpointConfiguration) : 
            base(AxataServicePoolEXTClient.GetBindingForEndpoint(endpointConfiguration), AxataServicePoolEXTClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public AxataServicePoolEXTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(AxataServicePoolEXTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public AxataServicePoolEXTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(AxataServicePoolEXTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public AxataServicePoolEXTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<updIntegrationTable_Res> updIntegrationTableAsync(updIntegrationTable_Req request)
    {
        return base.Channel.updIntegrationTableAsync(request);
    }
    
    public System.Threading.Tasks.Task<getDeliveryStatus_Res> addDeliveryStatusAsync(getDeliveryStatus_Req request)
    {
        return base.Channel.addDeliveryStatusAsync(request);
    }
    
    public System.Threading.Tasks.Task<getDeliveryCancel_Res> addDeliveryCancelAsync(getDeliveryCancel_Req request)
    {
        return base.Channel.addDeliveryCancelAsync(request);
    }
    
    public System.Threading.Tasks.Task<getViewData_Res> getViewDataAsync(getViewData_Req request)
    {
        return base.Channel.getViewDataAsync(request);
    }
    
    public System.Threading.Tasks.Task<addUlusSAS_Res> addUlusSASAsync(addUlusSAS_Req request)
    {
        return base.Channel.addUlusSASAsync(request);
    }
    
    public System.Threading.Tasks.Task<addATFPaletBlokeCoz_Res> addATFPaletBlokeCozAsync(addATFPaletBlokeCoz_Req request)
    {
        return base.Channel.addATFPaletBlokeCozAsync(request);
    }
    
    public System.Threading.Tasks.Task<addATFPaletBlokeCozList_Res> addATFPaletBlokeCozListAsync(addATFPaletBlokeCozList_Req request)
    {
        return base.Channel.addATFPaletBlokeCozListAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    #if !NET6_0_OR_GREATER
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    #endif
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAxataServicePoolEXT))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAxataServicePoolEXT))
        {
            return new System.ServiceModel.EndpointAddress("http://furpa-iis.furpa.local:8090/AxataServicePoolEXT.svc");
        }
        throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return AxataServicePoolEXTClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAxataServicePoolEXT);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return AxataServicePoolEXTClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAxataServicePoolEXT);
    }
    
    public enum EndpointConfiguration
    {
        
        BasicHttpBinding_IAxataServicePoolEXT,
    }
}
}
