namespace FurpaMerkezApi.Application.Modules.MalKabulIslemleri.MalKabuller.CompanyReceiving;

public sealed record CreateCompanyReceivingResponse(
    string DocumentSerie,
    int DocumentOrderNo,
    DateTime MovementDate,
    DateTime DocumentDate,
    string DocumentNo,
    int WarehouseNo,
    string CustomerCode,
    int LineCount,
    double TotalReceivedQuantity,
    double TotalOrderLinkedQuantity,
    double TotalOrderlessQuantity,
    double TotalOrderOverReceivedQuantity,
    double TotalAmount,
    string WriteConnectionName,
    IReadOnlyCollection<CreateCompanyReceivingLineResultDto> Lines,
    double TotalDispatchQuantity = 0d,
    double TotalNetAcceptedQuantity = 0d,
    double TotalReturnedQuantity = 0d,
    int AutoCreatedReturnLineCount = 0,
    string? AutoCreatedReturnDocumentSerie = null,
    int? AutoCreatedReturnDocumentOrderNo = null,
    string ReturnEDespatchStatus = "Yok");

public sealed record CreateCompanyReceivingLineResultDto(
    Guid MovementGuid,
    int SourceLineNo,
    int MovementLineNo,
    string StockCode,
    Guid? OrderGuid,
    bool IsOrderLinked,
    string ReceivingMode,
    double RequestedQuantity,
    double AcceptedQuantity,
    double OrderLinkedQuantity,
    double OrderlessQuantity,
    double OrderRemainingBefore,
    double OrderRemainingAfter,
    double DispatchQuantity = 0d,
    double PhysicalAcceptedQuantity = 0d,
    double ReturnQuantity = 0d,
    string ReturnStatus = "Yok",
    Guid? ReturnMovementGuid = null,
    string? ReturnDocumentSerie = null,
    int? ReturnDocumentOrderNo = null,
    string ReturnEDespatchStatus = "Yok");
