namespace FurpaMerkezApi.Application.Modules.AramaIslemleri.SearchCustomers;

public sealed record CustomerLookupItemDto(
    string CustomerCode,
    string CustomerName,
    string CustomerTitle,
    string CustomerDisplayName,
    string TaxNumber,
    string TaxIdentityNo,
    string TaxOfficeNo,
    string TaxOfficeName,
    string MainCustomerCode,
    string RegionCode,
    string GroupCode,
    string SectorCode,
    string RepresentativeCode,
    string RepresentativeName,
    string MobilePhone,
    string Email,
    int? InvoiceAddressNo,
    int? ShippingAddressNo,
    bool IsLocked,
    bool IsClosed,
    bool IsEInvoiceCustomer,
    bool IsEDespatchCustomer,
    int SameTaxCustomerCount,
    string SelectionLabel);
