namespace FurpaMerkezApi.Application.Modules.AramaIslemleri.ResolveBarcode;

public sealed record BarcodeResolutionDto(
    bool IsFound,
    string Barcode,
    int WarehouseNo,
    string? ScreenCode,
    string? ResolutionSource,
    string? StockCode,
    string? StockName,
    string? MatchedBarcode,
    string? PrimaryBarcode,
    string? CaseBarcode,
    double? UnitsPerCase,
    int? MatchedUnitPointer,
    string? MatchedUnitName,
    double? MatchedUnitMultiplier,
    bool IsBlocked,
    bool IsSalesBlocked,
    bool IsOrderBlocked,
    bool IsGoodsAcceptanceBlocked,
    bool IsUsableInScreen,
    string? UsabilityReason,
    string? DefaultSupplierCode,
    string? DefaultSupplierName,
    string? LookupBarcode = null,
    bool IsVariableWeightBarcode = false,
    double? EmbeddedQuantity = null,
    string? EmbeddedQuantityUnit = null,
    bool? IsBarcodeCheckDigitValid = null,
    string? BarcodeKind = null,
    bool IsPrimaryBarcode = false,
    bool IsCaseBarcode = false,
    bool IsAlternativeBarcode = false,
    double? MatchedUnitsPerCase = null,
    string? OperationType = null,
    int? TargetWarehouseNo = null,
    bool? IsAllowedForTargetWarehouse = null,
    string? TargetWarehouseReason = null,
    string? ProductModelCode = null,
    IReadOnlyCollection<string>? TargetWarehouseModelCodes = null,
    string? SupplierCode = null,
    bool? HasPurchaseRequirement = null,
    string? PurchaseRequirementReason = null,
    double? SalesPrice = null,
    int? PriceTypeCode = null,
    bool IsPassive = false,
    bool IsUsableInOperation = false,
    string? OperationDecision = null,
    IReadOnlyCollection<string>? Warnings = null,
    IReadOnlyCollection<string>? Errors = null,
    double? UnitMultiplier = null,
    double? PurchasePrice = null,
    double? PurchaseGrossPrice = null,
    string? PurchasePriceSource = null,
    string? PurchaseSupplierCode = null);
